// AUTOGENERATED, 09.04.2010 14:35:47
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl_NK
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class NKNUM
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(NKNUM));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSNKNUM
            {
                get { return "SYSNKNUM"; }
            }

            public static string BEZEICHNUNG
            {
                get { return "BEZEICHNUNG"; }
            }

            public static string LFDNR
            {
                get { return "LFDNR"; }
            }

            public static string MIN
            {
                get { return "MIN"; }
            }

            public static string MAX
            {
                get { return "MAX"; }
            }

            public static string FLAGRESET
            {
                get { return "FLAGRESET"; }
            }

            public static string FLAGOFLOWMES
            {
                get { return "FLAGOFLOWMES"; }
            }

            public static string EVLOFLOWMES
            {
                get { return "EVLOFLOWMES"; }
            }


			#endregion
        }

    }
}