//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cic.One.Web.luceneConfigServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cic-software.de/One", ConfigurationName="luceneConfigServiceReference.IluceneConfigService")]
    public interface IluceneConfigService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cic-software.de/One/IluceneConfigService/queueForIndexUpdate", ReplyAction="http://cic-software.de/One/IluceneConfigService/queueForIndexUpdateResponse")]
        void queueForIndexUpdate(string area, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cic-software.de/One/IluceneConfigService/startIndexer", ReplyAction="http://cic-software.de/One/IluceneConfigService/startIndexerResponse")]
        void startIndexer(CIC.ASS.Common.DTO.IndexedTable[] config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cic-software.de/One/IluceneConfigService/searchEntities", ReplyAction="http://cic-software.de/One/IluceneConfigService/searchEntitiesResponse")]
        CIC.ASS.SearchService.DTO.SearchEntityResult[] searchEntities(string query, string perole, string entities, string additionalQuery, CIC.ASS.Common.DTO.QueryPreprocessorConfig preprocConfig, string[] disabledperoles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cic-software.de/One/IluceneConfigService/suggest", ReplyAction="http://cic-software.de/One/IluceneConfigService/suggestResponse")]
        string[] suggest(string term);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IluceneConfigServiceChannel : Cic.One.Web.luceneConfigServiceReference.IluceneConfigService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IluceneConfigServiceClient : System.ServiceModel.ClientBase<Cic.One.Web.luceneConfigServiceReference.IluceneConfigService>, Cic.One.Web.luceneConfigServiceReference.IluceneConfigService {
        
        public IluceneConfigServiceClient() {
        }
        
        public IluceneConfigServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IluceneConfigServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluceneConfigServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IluceneConfigServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void queueForIndexUpdate(string area, long id) {
            base.Channel.queueForIndexUpdate(area, id);
        }
        
        public void startIndexer(CIC.ASS.Common.DTO.IndexedTable[] config) {
            base.Channel.startIndexer(config);
        }
        
        public CIC.ASS.SearchService.DTO.SearchEntityResult[] searchEntities(string query, string perole, string entities, string additionalQuery, CIC.ASS.Common.DTO.QueryPreprocessorConfig preprocConfig, string[] disabledperoles) {
            return base.Channel.searchEntities(query, perole, entities, additionalQuery, preprocConfig, disabledperoles);
        }
        
        public string[] suggest(string term) {
            return base.Channel.suggest(term);
        }
    }
}
