// AUTOGENERATED, 24.09.2009 11:54:49
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOiqueue
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class CFG
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(CFG));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSCFG
            {
                get { return "SYSCFG"; }
            }

            public static string CODE
            {
                get { return "CODE"; }
            }

            public static string BEZEICHNUNG
            {
                get { return "BEZEICHNUNG"; }
            }

            public static string OVERRIDEFLAG
            {
                get { return "OVERRIDEFLAG"; }
            }

            public static string SUPPLEMENTFLAG
            {
                get { return "SUPPLEMENTFLAG"; }
            }

            public static string ACTIVEFLAG
            {
                get { return "ACTIVEFLAG"; }
            }

            public static string INIREPLACEMENT
            {
                get { return "INIREPLACEMENT"; }
            }


			#endregion
        }

    }
}