using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Cic.OpenOne.Common.DTO;

namespace Cic.One.DTO
{
    /// <summary>
    /// Kalkulation WKT
    /// </summary>
    public class MycalcDto:EntityDto
    {
        public long sysmycalc { get; set; }

        override public String getEntityBezeichnung()
        {
            return bezeichnung + " " + hersteller+" "+bemerkung1;
        }

        /// <summary>
        /// Service Calculation
        /// </summary>
        public MycalcfsDto serviceKalkulation {get;set;}
        /// <summary>
        /// Object Equipment List
        /// </summary>
        public List<MycalcaustDto> equipment { get; set; }

        public long syswfuser { get; set; }
        public long syswf { get; set; }
        public DateTime? erstelltam { get; set; }
        public long sysvttyp { get; set; }
        public long sysobtyp { get; set; }
        public long syskalktyp { get; set; }
        public long sysin { get; set; }
        public long syshd { get; set; }
        public String identeg { get; set; }
        public String anrede { get; set; }
        public String name { get; set; }
        public String vorname { get; set; }
        public String strasse { get; set; }
        public String plz { get; set; }
        public String ort { get; set; }
        public int privatflag { get; set; }
        public String handy { get; set; }
        public String autotelefon { get; set; }
        public String fax { get; set; }
        public String telefon { get; set; }
        public String telefon1 { get; set; }
        public String telefon2 { get; set; }
        public String email { get; set; }
        public int geschlecht { get; set; }
        public DateTime? gebdatum { get; set; }
        public String zhd { get; set; }
        public String bemerkung1 { get; set; }
        public String bemerkung2 { get; set; }
        public long sysangebot { get; set; }
        public String angebot { get; set; }
        public String amortisation { get; set; }
        public long sysob { get; set; }
        public String objekt { get; set; }
        public String bezeichnung { get; set; }
        public String standort { get; set; }
        public String inventar { get; set; }
        public String fabrikat { get; set; }
        public String brief { get; set; }
        public int objektzustand { get; set; }
        public String hersteller { get; set; }
        public DateTime? baujahr { get; set; }
        public long ubnahmekm { get; set; }
        public long abnahmekm { get; set; }
        public long jahreskm { get; set; }
        public long kmtoleranz { get; set; }
        public long mikmbegrenz { get; set; }
        public double satzmehrkm { get; set; }
        public double satzminderkm { get; set; }
        public String ausstattung { get; set; }
        public String sonstiges { get; set; }
        public String farbei { get; set; }
        public String farbea { get; set; }
        public int polster { get; set; }
        public String felgen { get; set; }
        public int navi { get; set; }
        public int schiebdach { get; set; }
        public int klima { get; set; }
        public int automatik { get; set; }
        public int elfensterh { get; set; }
        public int zentralv { get; set; }
        public int radio { get; set; }
        public int cd { get; set; }
        public int anzahltueren { get; set; }
        public int anzahlsitze { get; set; }
        public int telefona { get; set; }
        public int kraftstoff { get; set; }
        public long ps { get; set; }
        public long kw { get; set; }
        public long ccm { get; set; }
        public long syswaehrung { get; set; }
        public long sysfwaehrung { get; set; }
        public long sysmwst { get; set; }
        public double bruttokredit { get; set; }
        public double fbruttokredit { get; set; }
        public double grund { get; set; }
        public double fgrund { get; set; }
        public double sonder { get; set; }
        public double fsonder { get; set; }
        public int spaket { get; set; }
        public double snovaf { get; set; }
        public double fsnovaf { get; set; }
        public double znovaf { get; set; }
        public double fznovaf { get; set; }
        public double spreis { get; set; }
        public double fspreis { get; set; }
        public double zubehoer { get; set; }
        public double fzubehoer { get; set; }
        public double zubehoerp { get; set; }
        public double zuabschlag1 { get; set; }
        public double fzuabschlag1 { get; set; }
        public double gesamt { get; set; }
        public double fgesamt { get; set; }
        public double rabatto { get; set; }
        public double frabatto { get; set; }
        public double rabattop { get; set; }
        public double subventiono { get; set; }
        public double fsubventiono { get; set; }
        public double investitiono { get; set; }
        public double finvestitiono { get; set; }
        public double skontoo { get; set; }
        public double fskontoo { get; set; }
        public double skontoop { get; set; }
        public double zubehoeror { get; set; }
        public double fzubehoeror { get; set; }
        public double zubehoerorp { get; set; }
        public double zuabschlag2 { get; set; }
        public double fzuabschlag2 { get; set; }
        public double bgextern { get; set; }
        public double fbgextern { get; set; }
        public double hdbeteil { get; set; }
        public double fhdbeteil { get; set; }
        public double werk { get; set; }
        public double fwerk { get; set; }
        public double rabattv { get; set; }
        public double frabattv { get; set; }
        public double rabattvp { get; set; }
        public double subventionv { get; set; }
        public double fsubventionv { get; set; }
        public double investitionv { get; set; }
        public double finvestitionv { get; set; }
        public double skontov { get; set; }
        public double fskontov { get; set; }
        public double skontovp { get; set; }
        public double zuabschlag3 { get; set; }
        public double fzuabschlag3 { get; set; }
        public double ahk { get; set; }
        public double fahk { get; set; }
        public double ahkkorr { get; set; }
        public double fahkkorr { get; set; }
        public double verrechnung { get; set; }
        public double fverrechnung { get; set; }
        public double anzahlung { get; set; }
        public double fanzahlung { get; set; }
        public double anzahlungp { get; set; }
        public double depot { get; set; }
        public double fdepot { get; set; }
        public int depotverr { get; set; }
        public double sz { get; set; }
        public double fsz { get; set; }
        public double szp { get; set; }
        public double sz2 { get; set; }
        public double zinssz { get; set; }
        public double rggebuehr { get; set; }
        public double frggebuehr { get; set; }
        public int rggverr { get; set; }
        public int subvention { get; set; }
        public double provision { get; set; }
        public double fprovision { get; set; }
        public double provisionp { get; set; }
        public double marge { get; set; }
        public double fmarge { get; set; }
        public double margep { get; set; }
        public double gebuehr { get; set; }
        public double fgebuehr { get; set; }
        public double rsv { get; set; }
        public double frsv { get; set; }
        public double disagio { get; set; }
        public double fdisagio { get; set; }
        public double zuabschlag4 { get; set; }
        public double fzuabschlag4 { get; set; }
        public double bgintern { get; set; }
        public double fbgintern { get; set; }
        public double rw { get; set; }
        public double frw { get; set; }
        public double rwp { get; set; }
        public double rwkorr { get; set; }
        public double frwkorr { get; set; }
        public double db { get; set; }
        public double fdb { get; set; }
        public double dbp { get; set; }
        public int lz { get; set; }
        public int lzvorlauf { get; set; }
        public int lz2 { get; set; }
        public int lzvorlauf2 { get; set; }
        public int ppy { get; set; }
        public double zins { get; set; }
        public double zinseff { get; set; }
        public double aibd { get; set; }
        public double rate { get; set; }
        public double frate { get; set; }
        public double faktor { get; set; }
        public double blockrate { get; set; }
        public double fblockrate { get; set; }
        public int modus { get; set; }
        public DateTime? beginn { get; set; }
        public DateTime? ende { get; set; }
        public DateTime? ersterate { get; set; }
        public DateTime? letzterate { get; set; }
        public DateTime? kursvaluta { get; set; }
        public double kurs { get; set; }
        public int flagbgbrutto { get; set; }
        public String objektvt { get; set; }
        public double rsv2 { get; set; }
        public double frsv2 { get; set; }
        public double rwhist { get; set; }
        public double rwkalk { get; set; }
        public double rwtabelle { get; set; }
        public int flagblock { get; set; }
        public DateTime? abweinzug { get; set; }
        public String matchcode { get; set; }
        public DateTime? beginnvorlauf { get; set; }
        public double ratestd { get; set; }
        public double zinscust { get; set; }
        public double zinscust2 { get; set; }
        public double disagiop { get; set; }
        public long sysvart { get; set; }
        public long sysvarttab { get; set; }
        public long sysvwaehrung { get; set; }
        public long sysadm { get; set; }
        public long sysgst { get; set; }
        public double zinscust3 { get; set; }
        public double extnom { get; set; }
        public double extnom2 { get; set; }
        public double exteff { get; set; }
        public double extpangv { get; set; }
        public double intzins1 { get; set; }
        public double intzins2 { get; set; }
        public double intzins3 { get; set; }
        public double intzins4 { get; set; }
        public double refizins1 { get; set; }
        public double refizins2 { get; set; }
        public double zinsanzk { get; set; }
        public double zinsanzh { get; set; }
        public double anzahlungk { get; set; }
        public double anzahlungh { get; set; }
        public double hrabatt { get; set; }
        public int ok { get; set; }
        public int flagsysvttyp { get; set; }
        public int flagsysobtyp { get; set; }
        public int flagsyskalktyp { get; set; }
        public double zinsdiffk { get; set; }
        public double zinsdiffh { get; set; }
        public double zinsint { get; set; }
        public double ahkhw { get; set; }
        public int stueckzahl { get; set; }
        public int flagmaster { get; set; }
        public int flagazkkalk { get; set; }
        public int flagazhkalk { get; set; }
        public double bwmarge1 { get; set; }
        public double bwmargep1 { get; set; }
        public double bwmarge2 { get; set; }
        public double bwmargep2 { get; set; }
        public double manfee { get; set; }
        public double manfeep { get; set; }
        public double iborauf { get; set; }
        public int flagopt1 { get; set; }
        public int flagopt2 { get; set; }
        public int flagopt3 { get; set; }
        public int flagopt4 { get; set; }
        public int flagopt5 { get; set; }
        public DateTime? syscreate { get; set; }
        public DateTime? syschange { get; set; }
        public String zustand { get; set; }
        public DateTime? zustandam { get; set; }
        public String schwacke { get; set; }
        public DateTime? schwackedatum { get; set; }
        public double fahrerbet { get; set; }
        public double fahrerbetp { get; set; }
        public double servicefee { get; set; }
        public DateTime? liefer { get; set; }
        public double bgexternb { get; set; }
        public double bgexternsteuer { get; set; }
        public double db1 { get; set; }
        public double db1p { get; set; }
        public int flagimpvt { get; set; }
        public int flagzollautobe { get; set; }
        public int flagbankautobe { get; set; }
        public int flagvermsteuer { get; set; }
        public int flagvermsteuerp { get; set; }
        public double registration { get; set; }
        public double kfzsteuer { get; set; }
        public double abschrnorm { get; set; }
        public double akzise { get; set; }
        public double akzisep { get; set; }
        public double leazahlvvp { get; set; }
        public double leazahlvvmszp { get; set; }
        public double mfpsz { get; set; }
        public int lza { get; set; }
        public double vprov { get; set; }
        public double vprovp { get; set; }
        public double bprov { get; set; }
        public double bprovp { get; set; }
        public double rateabschr { get; set; }
        public double versp { get; set; }
        public double diskontp { get; set; }
        public double abschrkoeffp { get; set; }
        public double vermsteuer { get; set; }
        public double vermsteuerp { get; set; }
        public double zinspa { get; set; }
        public double zollerl { get; set; }
        public double zollerlp { get; set; }
        public double zubehoernetto { get; set; }
        public double zubehoerbrutto { get; set; }
        public double zollgebuehr { get; set; }
        public double zollgebuehrp { get; set; }
        public long sysbankkd { get; set; }
        public long sysbanklf { get; set; }
        public double bgexternneuewaehrung { get; set; }
        public double vpreismsteuer { get; set; }
        public long sysbankprov { get; set; }
        public long syszinstab { get; set; }
        public long syspool { get; set; }
        public double poolkosten { get; set; }
        public double risikokosten { get; set; }
        public double kostengarant { get; set; }
        public int zinstyp { get; set; }
        public int fztyp { get; set; }
        public double lzkvor { get; set; }
        public double lz2kvor { get; set; }
        public double rkorrektur { get; set; }
        public int zylinder { get; set; }
        public long sysservpack { get; set; }
        public int flagservpack { get; set; }
        public double zubehoerorw { get; set; }
        public double zubehoerorwp { get; set; }
        public long sysrvt { get; set; }
        public DateTime? kursvalutahd { get; set; }
        public long syspartner { get; set; }
        public long syswfuserchange { get; set; }
        public double verbrauch_s { get; set; }
        public double verbrauch_90 { get; set; }
        public double verbrauch_d { get; set; }
        public long co2 { get; set; }
        public String typ { get; set; }
        public long kmstand { get; set; }
        public double paketpreis { get; set; }
        public String typfz { get; set; }
        public String wagentyp { get; set; }
        public String fgnr { get; set; }
        public String fznr { get; set; }
        public String gehnid { get; set; }
        public String fahrer { get; set; }
        public long sysit { get; set; }
        public double zubrabo { get; set; }
        public double zubrabop { get; set; }
        public double zubrabv { get; set; }
        public double zubrabvp { get; set; }
        public double pakete { get; set; }
        public double pakrabo { get; set; }
        public double pakrabop { get; set; }
        public double pakrabv { get; set; }
        public double pakrabvp { get; set; }
        public double sonzub { get; set; }
        public double sonzubrabo { get; set; }
        public double sonzubrabop { get; set; }
        public double sonzubrabv { get; set; }
        public double sonzubrabvp { get; set; }
        public double rwfzaufab { get; set; }
        public double rwfzaufabp { get; set; }
        public double rwzubaufab { get; set; }
        public double rwzubaufabp { get; set; }
        public double mehrkm { get; set; }
        public double mehrkmp { get; set; }
        public double minderkm { get; set; }
        public double minderkmp { get; set; }
        public double novap { get; set; }
        public double zins1 { get; set; }
        public double zins2 { get; set; }
        public double zins3 { get; set; }
        public double zins4 { get; set; }
        public double zins5 { get; set; }
        public double zins6 { get; set; }
        public double zins7 { get; set; }
        public double zins8 { get; set; }
        public double zins9 { get; set; }
        public double zins10 { get; set; }
        public double setupfee { get; set; }
        public double setupfeep { get; set; }
        public int ptyp { get; set; }
        public int typzins1 { get; set; }
        public int typzins2 { get; set; }
        public int typzins3 { get; set; }
        public int typzins4 { get; set; }
        public int typzins5 { get; set; }
        public int typzins6 { get; set; }
        public int typzins7 { get; set; }
        public int typzins8 { get; set; }
        public int typzins9 { get; set; }
        public int typzins10 { get; set; }
        public int pzmethode { get; set; }
        public int ppyz { get; set; }
        public double nerloese { get; set; }
        public double nova { get; set; }
        public double novazuab { get; set; }
        public double vprov2 { get; set; }
        public double vprov2p { get; set; }
        public double insvalue { get; set; }
        public double propvalue { get; set; }
        public long sysangkalk { get; set; }
        public double rwbase { get; set; }
        public double rwcrv { get; set; }
        public int calctarget { get; set; }
        public int holdfields { get; set; }
        public String notizen { get; set; }
        public long sysprproduct { get; set; }
        public double grundinkln { get; set; }
        public double paketeinkln { get; set; }
        public double sonzubinkln { get; set; }
        public double rsv3 { get; set; }
        public double rsv4 { get; set; }
        public double rsv5 { get; set; }

        public long sysfstypbsi { get; set; }
        public double mitfin { get; set; }


        public override long getEntityId()
        {
            return sysmycalc;
        }
    }
}
