// AUTOGENERATED, 26.01.2010 17:01:14
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Cic.OpenOne.Common.Util.Config;
namespace Cic.OpenLease.Model.DdEurotax
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class EurotaxExtendedEntities : EurotaxEntities
    {
    	
		
        #region Constructors
        public EurotaxExtendedEntities() :
            base(ConnectionStringBuilder.DeliverConnectionString(typeof (EurotaxEntities), "DdEurotax"))
            
        {
        }

        #endregion

		
     
    }
}
