//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zekbatchservice.xml.prechku.sys:15574/dvzekbatch/services/ZekBatchService", ConfigurationName="DAO.Auskunft.ZEKBatchRef.ZEKBatchService")]
    public interface ZEKBatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BatchInstructionError))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonBatchResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="closeContractsBatchReturn")]
        Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.BatchInstructionResponse closeContractsBatch(Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.IdentityDescriptor identityDescriptor, string batchRequestId, Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ContractClosureInstruction[] contracts);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BatchInstructionError))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonBatchResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="openContractsBatchReturn")]
        Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.BatchInstructionResponse openContractsBatch(Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.IdentityDescriptor identityDescriptor, string batchRequestId, Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ContractOpenInstruction[] contracts);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BatchInstructionError))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonBatchResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateContractsBatchReturn")]
        Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.BatchInstructionResponse updateContractsBatch(Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.IdentityDescriptor identityDescriptor, string batchRequestId, Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ContractUpdateInstruction[] contracts);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BatchInstructionError))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonBatchResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BasicObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="batchStatusReturn")]
        Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.BatchStatusResponse batchStatus(Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.IdentityDescriptor identityDescriptor, string batchRequestId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekTransactionService")]
    public partial class IdentityDescriptor : Model {
        
        private string clientUserIdField;
        
        private string nameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string clientUserId {
            get {
                return this.clientUserIdField;
            }
            set {
                this.clientUserIdField = value;
                this.RaisePropertyChanged("clientUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CommonBatchInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractUpdateInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractOpenInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractClosureInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(IdentityDescriptor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://base.sys.iqa")]
    public partial class Model : BasicModel {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Model))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CommonBatchInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractUpdateInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractOpenInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractClosureInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(IdentityDescriptor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://base.sys.iqa")]
    public abstract partial class BasicModel : BasicObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BasicModel))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Model))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CommonBatchInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractUpdateInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractOpenInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractClosureInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(IdentityDescriptor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://base.sys.iqa")]
    public partial class BasicObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class BatchInstructionError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerReferenceField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string customerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
                this.RaisePropertyChanged("customerReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekTransactionService")]
    public partial class TransactionError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string textField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekTransactionService")]
    public partial class ReturnCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string textField;
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BatchStatusResponse))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BatchInstructionResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public abstract partial class CommonBatchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReturnCode returnCodeField;
        
        private TransactionError transactionErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ReturnCode returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TransactionError transactionError {
            get {
                return this.transactionErrorField;
            }
            set {
                this.transactionErrorField = value;
                this.RaisePropertyChanged("transactionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class BatchStatusResponse : CommonBatchResponse {
        
        private System.Nullable<int> countProcessedErrorField;
        
        private System.Nullable<int> countProcessedSuccesfullyField;
        
        private BatchInstructionError[] errorListField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> countProcessedError {
            get {
                return this.countProcessedErrorField;
            }
            set {
                this.countProcessedErrorField = value;
                this.RaisePropertyChanged("countProcessedError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> countProcessedSuccesfully {
            get {
                return this.countProcessedSuccesfullyField;
            }
            set {
                this.countProcessedSuccesfullyField = value;
                this.RaisePropertyChanged("countProcessedSuccesfully");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public BatchInstructionError[] errorList {
            get {
                return this.errorListField;
            }
            set {
                this.errorListField = value;
                this.RaisePropertyChanged("errorList");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class BatchInstructionResponse : CommonBatchResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZEKTransactionService")]
    public partial class TeilzahlungsvertragDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> anfangsrateField;
        
        private System.Nullable<int> anzahlMonatlicheRatenField;
        
        private System.Nullable<int> bonitaetsCodeIKOField;
        
        private System.Nullable<int> bonitaetsCodeZEKField;
        
        private string datumBonitaetIKOField;
        
        private string datumBonitaetZEKField;
        
        private string datumErsteRateField;
        
        private string datumLetzteRateField;
        
        private System.Nullable<int> debtorRoleField;
        
        private System.Nullable<int> filialeField;
        
        private System.Nullable<int> herkunftField;
        
        private System.Nullable<int> kennzeichenField;
        
        private float kreditBetragField;
        
        private string kreditVertragIDField;
        
        private System.Nullable<float> monatsrateField;
        
        private System.Nullable<int> restwertField;
        
        private System.Nullable<int> sicherstellungsCodeField;
        
        private float theoRestSaldoField;
        
        private System.Nullable<int> vertragsStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> anfangsrate {
            get {
                return this.anfangsrateField;
            }
            set {
                this.anfangsrateField = value;
                this.RaisePropertyChanged("anfangsrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> anzahlMonatlicheRaten {
            get {
                return this.anzahlMonatlicheRatenField;
            }
            set {
                this.anzahlMonatlicheRatenField = value;
                this.RaisePropertyChanged("anzahlMonatlicheRaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeIKO {
            get {
                return this.bonitaetsCodeIKOField;
            }
            set {
                this.bonitaetsCodeIKOField = value;
                this.RaisePropertyChanged("bonitaetsCodeIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeZEK {
            get {
                return this.bonitaetsCodeZEKField;
            }
            set {
                this.bonitaetsCodeZEKField = value;
                this.RaisePropertyChanged("bonitaetsCodeZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetIKO {
            get {
                return this.datumBonitaetIKOField;
            }
            set {
                this.datumBonitaetIKOField = value;
                this.RaisePropertyChanged("datumBonitaetIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetZEK {
            get {
                return this.datumBonitaetZEKField;
            }
            set {
                this.datumBonitaetZEKField = value;
                this.RaisePropertyChanged("datumBonitaetZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumErsteRate {
            get {
                return this.datumErsteRateField;
            }
            set {
                this.datumErsteRateField = value;
                this.RaisePropertyChanged("datumErsteRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumLetzteRate {
            get {
                return this.datumLetzteRateField;
            }
            set {
                this.datumLetzteRateField = value;
                this.RaisePropertyChanged("datumLetzteRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> debtorRole {
            get {
                return this.debtorRoleField;
            }
            set {
                this.debtorRoleField = value;
                this.RaisePropertyChanged("debtorRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> filiale {
            get {
                return this.filialeField;
            }
            set {
                this.filialeField = value;
                this.RaisePropertyChanged("filiale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> herkunft {
            get {
                return this.herkunftField;
            }
            set {
                this.herkunftField = value;
                this.RaisePropertyChanged("herkunft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> kennzeichen {
            get {
                return this.kennzeichenField;
            }
            set {
                this.kennzeichenField = value;
                this.RaisePropertyChanged("kennzeichen");
            }
        }
        
        /// <remarks/>
        public float kreditBetrag {
            get {
                return this.kreditBetragField;
            }
            set {
                this.kreditBetragField = value;
                this.RaisePropertyChanged("kreditBetrag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kreditVertragID {
            get {
                return this.kreditVertragIDField;
            }
            set {
                this.kreditVertragIDField = value;
                this.RaisePropertyChanged("kreditVertragID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<float> monatsrate {
            get {
                return this.monatsrateField;
            }
            set {
                this.monatsrateField = value;
                this.RaisePropertyChanged("monatsrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> restwert {
            get {
                return this.restwertField;
            }
            set {
                this.restwertField = value;
                this.RaisePropertyChanged("restwert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> sicherstellungsCode {
            get {
                return this.sicherstellungsCodeField;
            }
            set {
                this.sicherstellungsCodeField = value;
                this.RaisePropertyChanged("sicherstellungsCode");
            }
        }
        
        /// <remarks/>
        public float theoRestSaldo {
            get {
                return this.theoRestSaldoField;
            }
            set {
                this.theoRestSaldoField = value;
                this.RaisePropertyChanged("theoRestSaldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> vertragsStatus {
            get {
                return this.vertragsStatusField;
            }
            set {
                this.vertragsStatusField = value;
                this.RaisePropertyChanged("vertragsStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class TeilzahlungskreditDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anzahlMonatlicheRatenField;
        
        private System.Nullable<int> bonitaetsCodeIKOField;
        
        private System.Nullable<int> bonitaetsCodeZEKField;
        
        private string datumBonitaetIKOField;
        
        private string datumBonitaetZEKField;
        
        private string datumErsteRateField;
        
        private string datumLetzteRateField;
        
        private System.Nullable<int> debtorRoleField;
        
        private System.Nullable<int> filialeField;
        
        private System.Nullable<int> herkunftField;
        
        private System.Nullable<int> kennzeichenField;
        
        private float kreditBetragField;
        
        private string kreditVertragIDField;
        
        private float monatsrateField;
        
        private System.Nullable<int> sicherstellungsCodeField;
        
        private float theoRestSaldoField;
        
        private System.Nullable<int> vertragsStatusField;
        
        /// <remarks/>
        public int anzahlMonatlicheRaten {
            get {
                return this.anzahlMonatlicheRatenField;
            }
            set {
                this.anzahlMonatlicheRatenField = value;
                this.RaisePropertyChanged("anzahlMonatlicheRaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeIKO {
            get {
                return this.bonitaetsCodeIKOField;
            }
            set {
                this.bonitaetsCodeIKOField = value;
                this.RaisePropertyChanged("bonitaetsCodeIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeZEK {
            get {
                return this.bonitaetsCodeZEKField;
            }
            set {
                this.bonitaetsCodeZEKField = value;
                this.RaisePropertyChanged("bonitaetsCodeZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetIKO {
            get {
                return this.datumBonitaetIKOField;
            }
            set {
                this.datumBonitaetIKOField = value;
                this.RaisePropertyChanged("datumBonitaetIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetZEK {
            get {
                return this.datumBonitaetZEKField;
            }
            set {
                this.datumBonitaetZEKField = value;
                this.RaisePropertyChanged("datumBonitaetZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumErsteRate {
            get {
                return this.datumErsteRateField;
            }
            set {
                this.datumErsteRateField = value;
                this.RaisePropertyChanged("datumErsteRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumLetzteRate {
            get {
                return this.datumLetzteRateField;
            }
            set {
                this.datumLetzteRateField = value;
                this.RaisePropertyChanged("datumLetzteRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> debtorRole {
            get {
                return this.debtorRoleField;
            }
            set {
                this.debtorRoleField = value;
                this.RaisePropertyChanged("debtorRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> filiale {
            get {
                return this.filialeField;
            }
            set {
                this.filialeField = value;
                this.RaisePropertyChanged("filiale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> herkunft {
            get {
                return this.herkunftField;
            }
            set {
                this.herkunftField = value;
                this.RaisePropertyChanged("herkunft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> kennzeichen {
            get {
                return this.kennzeichenField;
            }
            set {
                this.kennzeichenField = value;
                this.RaisePropertyChanged("kennzeichen");
            }
        }
        
        /// <remarks/>
        public float kreditBetrag {
            get {
                return this.kreditBetragField;
            }
            set {
                this.kreditBetragField = value;
                this.RaisePropertyChanged("kreditBetrag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kreditVertragID {
            get {
                return this.kreditVertragIDField;
            }
            set {
                this.kreditVertragIDField = value;
                this.RaisePropertyChanged("kreditVertragID");
            }
        }
        
        /// <remarks/>
        public float monatsrate {
            get {
                return this.monatsrateField;
            }
            set {
                this.monatsrateField = value;
                this.RaisePropertyChanged("monatsrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> sicherstellungsCode {
            get {
                return this.sicherstellungsCodeField;
            }
            set {
                this.sicherstellungsCodeField = value;
                this.RaisePropertyChanged("sicherstellungsCode");
            }
        }
        
        /// <remarks/>
        public float theoRestSaldo {
            get {
                return this.theoRestSaldoField;
            }
            set {
                this.theoRestSaldoField = value;
                this.RaisePropertyChanged("theoRestSaldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> vertragsStatus {
            get {
                return this.vertragsStatusField;
            }
            set {
                this.vertragsStatusField = value;
                this.RaisePropertyChanged("vertragsStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class LeasingMietvertragDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anzahlMonatlicheRatenField;
        
        private System.Nullable<int> anzahlungField;
        
        private System.Nullable<int> bonitaetsCodeIKOField;
        
        private System.Nullable<int> bonitaetsCodeZEKField;
        
        private string datumBonitaetIKOField;
        
        private string datumBonitaetZEKField;
        
        private string datumErsteRateField;
        
        private string datumLetzteRateField;
        
        private System.Nullable<int> debtorRoleField;
        
        private System.Nullable<int> ersteGrosseRateField;
        
        private System.Nullable<int> filialeField;
        
        private System.Nullable<int> grosseSchlussrateField;
        
        private System.Nullable<int> herkunftField;
        
        private System.Nullable<int> kennzeichenField;
        
        private float kreditBetragField;
        
        private string kreditVertragIDField;
        
        private float monatsrateField;
        
        private System.Nullable<int> restwertField;
        
        private System.Nullable<int> sicherstellungsCodeField;
        
        private float theoRestSaldoField;
        
        private System.Nullable<int> vertragsStatusField;
        
        /// <remarks/>
        public int anzahlMonatlicheRaten {
            get {
                return this.anzahlMonatlicheRatenField;
            }
            set {
                this.anzahlMonatlicheRatenField = value;
                this.RaisePropertyChanged("anzahlMonatlicheRaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> anzahlung {
            get {
                return this.anzahlungField;
            }
            set {
                this.anzahlungField = value;
                this.RaisePropertyChanged("anzahlung");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeIKO {
            get {
                return this.bonitaetsCodeIKOField;
            }
            set {
                this.bonitaetsCodeIKOField = value;
                this.RaisePropertyChanged("bonitaetsCodeIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeZEK {
            get {
                return this.bonitaetsCodeZEKField;
            }
            set {
                this.bonitaetsCodeZEKField = value;
                this.RaisePropertyChanged("bonitaetsCodeZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetIKO {
            get {
                return this.datumBonitaetIKOField;
            }
            set {
                this.datumBonitaetIKOField = value;
                this.RaisePropertyChanged("datumBonitaetIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetZEK {
            get {
                return this.datumBonitaetZEKField;
            }
            set {
                this.datumBonitaetZEKField = value;
                this.RaisePropertyChanged("datumBonitaetZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumErsteRate {
            get {
                return this.datumErsteRateField;
            }
            set {
                this.datumErsteRateField = value;
                this.RaisePropertyChanged("datumErsteRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumLetzteRate {
            get {
                return this.datumLetzteRateField;
            }
            set {
                this.datumLetzteRateField = value;
                this.RaisePropertyChanged("datumLetzteRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> debtorRole {
            get {
                return this.debtorRoleField;
            }
            set {
                this.debtorRoleField = value;
                this.RaisePropertyChanged("debtorRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> ersteGrosseRate {
            get {
                return this.ersteGrosseRateField;
            }
            set {
                this.ersteGrosseRateField = value;
                this.RaisePropertyChanged("ersteGrosseRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> filiale {
            get {
                return this.filialeField;
            }
            set {
                this.filialeField = value;
                this.RaisePropertyChanged("filiale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> grosseSchlussrate {
            get {
                return this.grosseSchlussrateField;
            }
            set {
                this.grosseSchlussrateField = value;
                this.RaisePropertyChanged("grosseSchlussrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> herkunft {
            get {
                return this.herkunftField;
            }
            set {
                this.herkunftField = value;
                this.RaisePropertyChanged("herkunft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> kennzeichen {
            get {
                return this.kennzeichenField;
            }
            set {
                this.kennzeichenField = value;
                this.RaisePropertyChanged("kennzeichen");
            }
        }
        
        /// <remarks/>
        public float kreditBetrag {
            get {
                return this.kreditBetragField;
            }
            set {
                this.kreditBetragField = value;
                this.RaisePropertyChanged("kreditBetrag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kreditVertragID {
            get {
                return this.kreditVertragIDField;
            }
            set {
                this.kreditVertragIDField = value;
                this.RaisePropertyChanged("kreditVertragID");
            }
        }
        
        /// <remarks/>
        public float monatsrate {
            get {
                return this.monatsrateField;
            }
            set {
                this.monatsrateField = value;
                this.RaisePropertyChanged("monatsrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> restwert {
            get {
                return this.restwertField;
            }
            set {
                this.restwertField = value;
                this.RaisePropertyChanged("restwert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> sicherstellungsCode {
            get {
                return this.sicherstellungsCodeField;
            }
            set {
                this.sicherstellungsCodeField = value;
                this.RaisePropertyChanged("sicherstellungsCode");
            }
        }
        
        /// <remarks/>
        public float theoRestSaldo {
            get {
                return this.theoRestSaldoField;
            }
            set {
                this.theoRestSaldoField = value;
                this.RaisePropertyChanged("theoRestSaldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> vertragsStatus {
            get {
                return this.vertragsStatusField;
            }
            set {
                this.vertragsStatusField = value;
                this.RaisePropertyChanged("vertragsStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class KontokorrentkreditDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> beanspruchterKreditProzentField;
        
        private System.Nullable<int> bonitaetsCodeIKOField;
        
        private System.Nullable<int> bonitaetsCodeZEKField;
        
        private string datumBonitaetIKOField;
        
        private string datumBonitaetZEKField;
        
        private string datumVertragsBeginnField;
        
        private string datumVertragsEndeField;
        
        private System.Nullable<int> debtorRoleField;
        
        private System.Nullable<int> filialeField;
        
        private System.Nullable<int> herkunftField;
        
        private System.Nullable<int> kennzeichenField;
        
        private float kreditLimiteField;
        
        private string kreditVertragIDField;
        
        private System.Nullable<int> sicherstellungsCodeField;
        
        private float theoRestSaldoField;
        
        private int vertragsStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> beanspruchterKreditProzent {
            get {
                return this.beanspruchterKreditProzentField;
            }
            set {
                this.beanspruchterKreditProzentField = value;
                this.RaisePropertyChanged("beanspruchterKreditProzent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeIKO {
            get {
                return this.bonitaetsCodeIKOField;
            }
            set {
                this.bonitaetsCodeIKOField = value;
                this.RaisePropertyChanged("bonitaetsCodeIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeZEK {
            get {
                return this.bonitaetsCodeZEKField;
            }
            set {
                this.bonitaetsCodeZEKField = value;
                this.RaisePropertyChanged("bonitaetsCodeZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetIKO {
            get {
                return this.datumBonitaetIKOField;
            }
            set {
                this.datumBonitaetIKOField = value;
                this.RaisePropertyChanged("datumBonitaetIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetZEK {
            get {
                return this.datumBonitaetZEKField;
            }
            set {
                this.datumBonitaetZEKField = value;
                this.RaisePropertyChanged("datumBonitaetZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumVertragsBeginn {
            get {
                return this.datumVertragsBeginnField;
            }
            set {
                this.datumVertragsBeginnField = value;
                this.RaisePropertyChanged("datumVertragsBeginn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumVertragsEnde {
            get {
                return this.datumVertragsEndeField;
            }
            set {
                this.datumVertragsEndeField = value;
                this.RaisePropertyChanged("datumVertragsEnde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> debtorRole {
            get {
                return this.debtorRoleField;
            }
            set {
                this.debtorRoleField = value;
                this.RaisePropertyChanged("debtorRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> filiale {
            get {
                return this.filialeField;
            }
            set {
                this.filialeField = value;
                this.RaisePropertyChanged("filiale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> herkunft {
            get {
                return this.herkunftField;
            }
            set {
                this.herkunftField = value;
                this.RaisePropertyChanged("herkunft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> kennzeichen {
            get {
                return this.kennzeichenField;
            }
            set {
                this.kennzeichenField = value;
                this.RaisePropertyChanged("kennzeichen");
            }
        }
        
        /// <remarks/>
        public float kreditLimite {
            get {
                return this.kreditLimiteField;
            }
            set {
                this.kreditLimiteField = value;
                this.RaisePropertyChanged("kreditLimite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kreditVertragID {
            get {
                return this.kreditVertragIDField;
            }
            set {
                this.kreditVertragIDField = value;
                this.RaisePropertyChanged("kreditVertragID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> sicherstellungsCode {
            get {
                return this.sicherstellungsCodeField;
            }
            set {
                this.sicherstellungsCodeField = value;
                this.RaisePropertyChanged("sicherstellungsCode");
            }
        }
        
        /// <remarks/>
        public float theoRestSaldo {
            get {
                return this.theoRestSaldoField;
            }
            set {
                this.theoRestSaldoField = value;
                this.RaisePropertyChanged("theoRestSaldo");
            }
        }
        
        /// <remarks/>
        public int vertragsStatus {
            get {
                return this.vertragsStatusField;
            }
            set {
                this.vertragsStatusField = value;
                this.RaisePropertyChanged("vertragsStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class Festkredit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> bonitaetsCodeIKOField;
        
        private System.Nullable<int> bonitaetsCodeZEKField;
        
        private string datumBonitaetIKOField;
        
        private string datumBonitaetZEKField;
        
        private string datumVertragsBeginnField;
        
        private string datumVertragsEndeField;
        
        private System.Nullable<int> debtorRoleField;
        
        private System.Nullable<int> filialeField;
        
        private System.Nullable<int> herkunftField;
        
        private System.Nullable<int> kennzeichenField;
        
        private float kreditBetragField;
        
        private string kreditVertragIDField;
        
        private System.Nullable<int> sicherstellungsCodeField;
        
        private float theoRestSaldoField;
        
        private System.Nullable<int> vertragsStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeIKO {
            get {
                return this.bonitaetsCodeIKOField;
            }
            set {
                this.bonitaetsCodeIKOField = value;
                this.RaisePropertyChanged("bonitaetsCodeIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeZEK {
            get {
                return this.bonitaetsCodeZEKField;
            }
            set {
                this.bonitaetsCodeZEKField = value;
                this.RaisePropertyChanged("bonitaetsCodeZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetIKO {
            get {
                return this.datumBonitaetIKOField;
            }
            set {
                this.datumBonitaetIKOField = value;
                this.RaisePropertyChanged("datumBonitaetIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetZEK {
            get {
                return this.datumBonitaetZEKField;
            }
            set {
                this.datumBonitaetZEKField = value;
                this.RaisePropertyChanged("datumBonitaetZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumVertragsBeginn {
            get {
                return this.datumVertragsBeginnField;
            }
            set {
                this.datumVertragsBeginnField = value;
                this.RaisePropertyChanged("datumVertragsBeginn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumVertragsEnde {
            get {
                return this.datumVertragsEndeField;
            }
            set {
                this.datumVertragsEndeField = value;
                this.RaisePropertyChanged("datumVertragsEnde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> debtorRole {
            get {
                return this.debtorRoleField;
            }
            set {
                this.debtorRoleField = value;
                this.RaisePropertyChanged("debtorRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> filiale {
            get {
                return this.filialeField;
            }
            set {
                this.filialeField = value;
                this.RaisePropertyChanged("filiale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> herkunft {
            get {
                return this.herkunftField;
            }
            set {
                this.herkunftField = value;
                this.RaisePropertyChanged("herkunft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> kennzeichen {
            get {
                return this.kennzeichenField;
            }
            set {
                this.kennzeichenField = value;
                this.RaisePropertyChanged("kennzeichen");
            }
        }
        
        /// <remarks/>
        public float kreditBetrag {
            get {
                return this.kreditBetragField;
            }
            set {
                this.kreditBetragField = value;
                this.RaisePropertyChanged("kreditBetrag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kreditVertragID {
            get {
                return this.kreditVertragIDField;
            }
            set {
                this.kreditVertragIDField = value;
                this.RaisePropertyChanged("kreditVertragID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> sicherstellungsCode {
            get {
                return this.sicherstellungsCodeField;
            }
            set {
                this.sicherstellungsCodeField = value;
                this.RaisePropertyChanged("sicherstellungsCode");
            }
        }
        
        /// <remarks/>
        public float theoRestSaldo {
            get {
                return this.theoRestSaldoField;
            }
            set {
                this.theoRestSaldoField = value;
                this.RaisePropertyChanged("theoRestSaldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> vertragsStatus {
            get {
                return this.vertragsStatusField;
            }
            set {
                this.vertragsStatusField = value;
                this.RaisePropertyChanged("vertragsStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class BardarlehenDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anzahlMonatlicheRatenField;
        
        private System.Nullable<int> bonitaetsCodeIKOField;
        
        private System.Nullable<int> bonitaetsCodeZEKField;
        
        private string datumBonitaetIKOField;
        
        private string datumBonitaetZEKField;
        
        private string datumErsteRateField;
        
        private string datumLetzteRateField;
        
        private System.Nullable<int> debtorRoleField;
        
        private System.Nullable<int> filialeField;
        
        private System.Nullable<int> herkunftField;
        
        private System.Nullable<int> kennzeichenField;
        
        private float kreditBetragField;
        
        private string kreditVertragIDField;
        
        private float monatsrateField;
        
        private System.Nullable<int> sicherstellungsCodeField;
        
        private float theoRestSaldoField;
        
        private System.Nullable<int> vertragsStatusField;
        
        /// <remarks/>
        public int anzahlMonatlicheRaten {
            get {
                return this.anzahlMonatlicheRatenField;
            }
            set {
                this.anzahlMonatlicheRatenField = value;
                this.RaisePropertyChanged("anzahlMonatlicheRaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeIKO {
            get {
                return this.bonitaetsCodeIKOField;
            }
            set {
                this.bonitaetsCodeIKOField = value;
                this.RaisePropertyChanged("bonitaetsCodeIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeZEK {
            get {
                return this.bonitaetsCodeZEKField;
            }
            set {
                this.bonitaetsCodeZEKField = value;
                this.RaisePropertyChanged("bonitaetsCodeZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetIKO {
            get {
                return this.datumBonitaetIKOField;
            }
            set {
                this.datumBonitaetIKOField = value;
                this.RaisePropertyChanged("datumBonitaetIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetZEK {
            get {
                return this.datumBonitaetZEKField;
            }
            set {
                this.datumBonitaetZEKField = value;
                this.RaisePropertyChanged("datumBonitaetZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumErsteRate {
            get {
                return this.datumErsteRateField;
            }
            set {
                this.datumErsteRateField = value;
                this.RaisePropertyChanged("datumErsteRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumLetzteRate {
            get {
                return this.datumLetzteRateField;
            }
            set {
                this.datumLetzteRateField = value;
                this.RaisePropertyChanged("datumLetzteRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> debtorRole {
            get {
                return this.debtorRoleField;
            }
            set {
                this.debtorRoleField = value;
                this.RaisePropertyChanged("debtorRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> filiale {
            get {
                return this.filialeField;
            }
            set {
                this.filialeField = value;
                this.RaisePropertyChanged("filiale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> herkunft {
            get {
                return this.herkunftField;
            }
            set {
                this.herkunftField = value;
                this.RaisePropertyChanged("herkunft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> kennzeichen {
            get {
                return this.kennzeichenField;
            }
            set {
                this.kennzeichenField = value;
                this.RaisePropertyChanged("kennzeichen");
            }
        }
        
        /// <remarks/>
        public float kreditBetrag {
            get {
                return this.kreditBetragField;
            }
            set {
                this.kreditBetragField = value;
                this.RaisePropertyChanged("kreditBetrag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kreditVertragID {
            get {
                return this.kreditVertragIDField;
            }
            set {
                this.kreditVertragIDField = value;
                this.RaisePropertyChanged("kreditVertragID");
            }
        }
        
        /// <remarks/>
        public float monatsrate {
            get {
                return this.monatsrateField;
            }
            set {
                this.monatsrateField = value;
                this.RaisePropertyChanged("monatsrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> sicherstellungsCode {
            get {
                return this.sicherstellungsCodeField;
            }
            set {
                this.sicherstellungsCodeField = value;
                this.RaisePropertyChanged("sicherstellungsCode");
            }
        }
        
        /// <remarks/>
        public float theoRestSaldo {
            get {
                return this.theoRestSaldoField;
            }
            set {
                this.theoRestSaldoField = value;
                this.RaisePropertyChanged("theoRestSaldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> vertragsStatus {
            get {
                return this.vertragsStatusField;
            }
            set {
                this.vertragsStatusField = value;
                this.RaisePropertyChanged("vertragsStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractUpdateInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractOpenInstruction))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ContractClosureInstruction))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.batch.zkb.appl.ch")]
    public abstract partial class CommonBatchInstruction : Model {
        
        private string customerReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string customerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
                this.RaisePropertyChanged("customerReference");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class ContractUpdateInstruction : CommonBatchInstruction {
        
        private BardarlehenDescription bardarlehenField;
        
        private Festkredit festkreditField;
        
        private KontokorrentkreditDescription kontokorrentkreditField;
        
        private LeasingMietvertragDescription leasingMietvertragField;
        
        private TeilzahlungskreditDescription teilzahlungskreditField;
        
        private TeilzahlungsvertragDescription teilzahlungsvertragField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public BardarlehenDescription bardarlehen {
            get {
                return this.bardarlehenField;
            }
            set {
                this.bardarlehenField = value;
                this.RaisePropertyChanged("bardarlehen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Festkredit festkredit {
            get {
                return this.festkreditField;
            }
            set {
                this.festkreditField = value;
                this.RaisePropertyChanged("festkredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public KontokorrentkreditDescription kontokorrentkredit {
            get {
                return this.kontokorrentkreditField;
            }
            set {
                this.kontokorrentkreditField = value;
                this.RaisePropertyChanged("kontokorrentkredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public LeasingMietvertragDescription leasingMietvertrag {
            get {
                return this.leasingMietvertragField;
            }
            set {
                this.leasingMietvertragField = value;
                this.RaisePropertyChanged("leasingMietvertrag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TeilzahlungskreditDescription teilzahlungskredit {
            get {
                return this.teilzahlungskreditField;
            }
            set {
                this.teilzahlungskreditField = value;
                this.RaisePropertyChanged("teilzahlungskredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TeilzahlungsvertragDescription teilzahlungsvertrag {
            get {
                return this.teilzahlungsvertragField;
            }
            set {
                this.teilzahlungsvertragField = value;
                this.RaisePropertyChanged("teilzahlungsvertrag");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class ContractOpenInstruction : CommonBatchInstruction {
        
        private BardarlehenDescription bardarlehenField;
        
        private Festkredit festkreditField;
        
        private KontokorrentkreditDescription kontokorrentkreditField;
        
        private string kreditGesuchIDField;
        
        private string kundenIdField;
        
        private LeasingMietvertragDescription leasingMietvertragField;
        
        private TeilzahlungskreditDescription teilzahlungskreditField;
        
        private TeilzahlungsvertragDescription teilzahlungsvertragField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public BardarlehenDescription bardarlehen {
            get {
                return this.bardarlehenField;
            }
            set {
                this.bardarlehenField = value;
                this.RaisePropertyChanged("bardarlehen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Festkredit festkredit {
            get {
                return this.festkreditField;
            }
            set {
                this.festkreditField = value;
                this.RaisePropertyChanged("festkredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public KontokorrentkreditDescription kontokorrentkredit {
            get {
                return this.kontokorrentkreditField;
            }
            set {
                this.kontokorrentkreditField = value;
                this.RaisePropertyChanged("kontokorrentkredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kreditGesuchID {
            get {
                return this.kreditGesuchIDField;
            }
            set {
                this.kreditGesuchIDField = value;
                this.RaisePropertyChanged("kreditGesuchID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kundenId {
            get {
                return this.kundenIdField;
            }
            set {
                this.kundenIdField = value;
                this.RaisePropertyChanged("kundenId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public LeasingMietvertragDescription leasingMietvertrag {
            get {
                return this.leasingMietvertragField;
            }
            set {
                this.leasingMietvertragField = value;
                this.RaisePropertyChanged("leasingMietvertrag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TeilzahlungskreditDescription teilzahlungskredit {
            get {
                return this.teilzahlungskreditField;
            }
            set {
                this.teilzahlungskreditField = value;
                this.RaisePropertyChanged("teilzahlungskredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TeilzahlungsvertragDescription teilzahlungsvertrag {
            get {
                return this.teilzahlungsvertragField;
            }
            set {
                this.teilzahlungsvertragField = value;
                this.RaisePropertyChanged("teilzahlungsvertrag");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ZekBatchService")]
    public partial class ContractClosureInstruction : CommonBatchInstruction {
        
        private System.Nullable<int> bonitaetsCodeIKOField;
        
        private System.Nullable<int> bonitaetsCodeZEKField;
        
        private System.Nullable<int> contractTypeField;
        
        private string datumBonitaetIKOField;
        
        private string datumBonitaetZEKField;
        
        private string kreditVertragIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeIKO {
            get {
                return this.bonitaetsCodeIKOField;
            }
            set {
                this.bonitaetsCodeIKOField = value;
                this.RaisePropertyChanged("bonitaetsCodeIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> bonitaetsCodeZEK {
            get {
                return this.bonitaetsCodeZEKField;
            }
            set {
                this.bonitaetsCodeZEKField = value;
                this.RaisePropertyChanged("bonitaetsCodeZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> contractType {
            get {
                return this.contractTypeField;
            }
            set {
                this.contractTypeField = value;
                this.RaisePropertyChanged("contractType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetIKO {
            get {
                return this.datumBonitaetIKOField;
            }
            set {
                this.datumBonitaetIKOField = value;
                this.RaisePropertyChanged("datumBonitaetIKO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string datumBonitaetZEK {
            get {
                return this.datumBonitaetZEKField;
            }
            set {
                this.datumBonitaetZEKField = value;
                this.RaisePropertyChanged("datumBonitaetZEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string kreditVertragID {
            get {
                return this.kreditVertragIDField;
            }
            set {
                this.kreditVertragIDField = value;
                this.RaisePropertyChanged("kreditVertragID");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZEKBatchServiceChannel : Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ZEKBatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZEKBatchServiceClient : System.ServiceModel.ClientBase<Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ZEKBatchService>, Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ZEKBatchService {
        
        public ZEKBatchServiceClient() {
        }
        
        public ZEKBatchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZEKBatchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZEKBatchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZEKBatchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.BatchInstructionResponse closeContractsBatch(Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.IdentityDescriptor identityDescriptor, string batchRequestId, Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ContractClosureInstruction[] contracts) {
            return base.Channel.closeContractsBatch(identityDescriptor, batchRequestId, contracts);
        }
        
        public Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.BatchInstructionResponse openContractsBatch(Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.IdentityDescriptor identityDescriptor, string batchRequestId, Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ContractOpenInstruction[] contracts) {
            return base.Channel.openContractsBatch(identityDescriptor, batchRequestId, contracts);
        }
        
        public Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.BatchInstructionResponse updateContractsBatch(Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.IdentityDescriptor identityDescriptor, string batchRequestId, Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.ContractUpdateInstruction[] contracts) {
            return base.Channel.updateContractsBatch(identityDescriptor, batchRequestId, contracts);
        }
        
        public Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.BatchStatusResponse batchStatus(Cic.OpenOne.GateBANKNOW.Common.DAO.Auskunft.ZEKBatchRef.IdentityDescriptor identityDescriptor, string batchRequestId) {
            return base.Channel.batchStatus(identityDescriptor, batchRequestId);
        }
    }
}
