// AUTOGENERATED, 24.09.2009 11:54:49
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Cic.OpenOne.Common.Util.Config;
namespace Cic.OpenLease.Model.DdOiqueue
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class OiqueueExtendedEntities : OiqueueEntities
    {
    	
		
        
        public OiqueueExtendedEntities() :
             base(ConnectionStringBuilder.DeliverConnectionString(typeof (OiqueueEntities), "DdOiqueue"))
            
        {
        }

    }
}
