// AUTOGENERATED, 18.11.2010 15:27:36
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ADRV
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ADRV));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSADRV
            {
                get { return "SYSADRV"; }
            }

            public static string PROCESSCODE
            {
                get { return "PROCESSCODE"; }
            }

            public static string REQUESTDATE
            {
                get { return "REQUESTDATE"; }
            }

            public static string REQUESTTIME
            {
                get { return "REQUESTTIME"; }
            }

            public static string REQUESTUSER
            {
                get { return "REQUESTUSER"; }
            }

            public static string RESPONSEDATE
            {
                get { return "RESPONSEDATE"; }
            }

            public static string RESPONSETIME
            {
                get { return "RESPONSETIME"; }
            }

            public static string FEHLERCODE
            {
                get { return "FEHLERCODE"; }
            }

            public static string FEHLERNUMMER
            {
                get { return "FEHLERNUMMER"; }
            }

            public static string FEHLERMELDUNG
            {
                get { return "FEHLERMELDUNG"; }
            }

            public static string VERCODE
            {
                get { return "VERCODE"; }
            }

            public static string VERCODEERW
            {
                get { return "VERCODEERW"; }
            }


			#endregion
        }

    }
}