// AUTOGENERATED, 18.11.2010 15:27:36
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ANGABL
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ANGABL));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSANGABL
            {
                get { return "SYSANGABL"; }
            }

            public static string SYSANGEBOT
            {
                get { return "SYSANGEBOT"; }
            }

            public static string SYSVORANGEBOT
            {
                get { return "SYSVORANGEBOT"; }
            }

            public static string KONTONR
            {
                get { return "KONTONR"; }
            }

            public static string SYSBN
            {
                get { return "SYSBN"; }
            }

            public static string BANK
            {
                get { return "BANK"; }
            }

            public static string BLZ
            {
                get { return "BLZ"; }
            }

            public static string SYSLAND
            {
                get { return "SYSLAND"; }
            }

            public static string IBAN
            {
                get { return "IBAN"; }
            }

            public static string BIC
            {
                get { return "BIC"; }
            }

            public static string EMPFAENGER
            {
                get { return "EMPFAENGER"; }
            }

            public static string STRASSE
            {
                get { return "STRASSE"; }
            }

            public static string PLZ
            {
                get { return "PLZ"; }
            }

            public static string ORT
            {
                get { return "ORT"; }
            }

            public static string INTNUMMER
            {
                get { return "INTNUMMER"; }
            }

            public static string BETRAG
            {
                get { return "BETRAG"; }
            }

            public static string FLAGINTEXT
            {
                get { return "FLAGINTEXT"; }
            }

            public static string BEMERKUNG
            {
                get { return "BEMERKUNG"; }
            }

            public static string BETRAGEXT
            {
                get { return "BETRAGEXT"; }
            }

            public static string DATKALK
            {
                get { return "DATKALK"; }
            }

            public static string DATKALKPER
            {
                get { return "DATKALKPER"; }
            }

            public static string TYP
            {
                get { return "TYP"; }
            }

            public static string FREMDANGEBOT
            {
                get { return "FREMDANGEBOT"; }
            }

            public static string SYSAUFTRAG
            {
                get { return "SYSAUFTRAG"; }
            }


			#endregion
        }

    }
}