// AUTOGENERATED, 18.11.2010 15:27:37
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ANGKALKFS
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ANGKALKFS));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSANGKALKFS
            {
                get { return "SYSANGKALKFS"; }
            }

            public static string VALUTA
            {
                get { return "VALUTA"; }
            }

            public static string SERVICEFEE
            {
                get { return "SERVICEFEE"; }
            }

            public static string BAILPRICE
            {
                get { return "BAILPRICE"; }
            }

            public static string HANDOVERPRICE
            {
                get { return "HANDOVERPRICE"; }
            }

            public static string SYSVSTYP
            {
                get { return "SYSVSTYP"; }
            }

            public static string SUMVK
            {
                get { return "SUMVK"; }
            }

            public static string SUMHP
            {
                get { return "SUMHP"; }
            }

            public static string PASSINSURANCE
            {
                get { return "PASSINSURANCE"; }
            }

            public static string PARKDAMAGE
            {
                get { return "PARKDAMAGE"; }
            }

            public static string SECURITIES
            {
                get { return "SECURITIES"; }
            }

            public static string TAXFREEFLAG
            {
                get { return "TAXFREEFLAG"; }
            }

            public static string SYSSTAAT
            {
                get { return "SYSSTAAT"; }
            }

            public static string ORIGINOPTION
            {
                get { return "ORIGINOPTION"; }
            }

            public static string FUELFLAG
            {
                get { return "FUELFLAG"; }
            }

            public static string FUELPRICE
            {
                get { return "FUELPRICE"; }
            }

            public static string TIRESFLAG
            {
                get { return "TIRESFLAG"; }
            }

            public static string STIRESCODE
            {
                get { return "STIRESCODE"; }
            }

            public static string STIRESTEXT
            {
                get { return "STIRESTEXT"; }
            }

            public static string STIRESCOUNT
            {
                get { return "STIRESCOUNT"; }
            }

            public static string STIRESPRICE
            {
                get { return "STIRESPRICE"; }
            }

            public static string WTIRESCODE
            {
                get { return "WTIRESCODE"; }
            }

            public static string WTIRESTEXT
            {
                get { return "WTIRESTEXT"; }
            }

            public static string WTIRESCOUNT
            {
                get { return "WTIRESCOUNT"; }
            }

            public static string WTIRESPRICE
            {
                get { return "WTIRESPRICE"; }
            }

            public static string TTIRESPRICE
            {
                get { return "TTIRESPRICE"; }
            }

            public static string TIRESSTORAGE
            {
                get { return "TIRESSTORAGE"; }
            }

            public static string TIRESSTORAGEFLAG
            {
                get { return "TIRESSTORAGEFLAG"; }
            }

            public static string BSERVICECOUNT
            {
                get { return "BSERVICECOUNT"; }
            }

            public static string BSERVICEFLAG
            {
                get { return "BSERVICEFLAG"; }
            }

            public static string BSERVICEPRICE
            {
                get { return "BSERVICEPRICE"; }
            }

            public static string MAINTENANCE
            {
                get { return "MAINTENANCE"; }
            }

            public static string MAINTENANCEFLAG
            {
                get { return "MAINTENANCEFLAG"; }
            }

            public static string MAINTENANCEMKM
            {
                get { return "MAINTENANCEMKM"; }
            }

            public static string MAINTENANCELKM
            {
                get { return "MAINTENANCELKM"; }
            }

            public static string REPCARCOUNT
            {
                get { return "REPCARCOUNT"; }
            }

            public static string REPCARPRICE
            {
                get { return "REPCARPRICE"; }
            }

            public static string REPCARFLAG
            {
                get { return "REPCARFLAG"; }
            }

            public static string DELIVERY
            {
                get { return "DELIVERY"; }
            }

            public static string DELIVERYFLAG
            {
                get { return "DELIVERYFLAG"; }
            }

            public static string CARWASHCOUNT
            {
                get { return "CARWASHCOUNT"; }
            }

            public static string CARWASHFLAG
            {
                get { return "CARWASHFLAG"; }
            }

            public static string CARWASHPRICE
            {
                get { return "CARWASHPRICE"; }
            }

            public static string MGMNTFEEFLAG
            {
                get { return "MGMNTFEEFLAG"; }
            }

            public static string VIGNETTENFLAG
            {
                get { return "VIGNETTENFLAG"; }
            }

            public static string VIGNETTEN
            {
                get { return "VIGNETTEN"; }
            }

            public static string VATFLAG
            {
                get { return "VATFLAG"; }
            }

            public static string FUELSYSFSTYP
            {
                get { return "FUELSYSFSTYP"; }
            }

            public static string FUELZINSFLAG
            {
                get { return "FUELZINSFLAG"; }
            }

            public static string TIRESSYSFSTYP
            {
                get { return "TIRESSYSFSTYP"; }
            }

            public static string TIRESZINSFLAG
            {
                get { return "TIRESZINSFLAG"; }
            }

            public static string TIRESZINS
            {
                get { return "TIRESZINS"; }
            }

            public static string TIRESSTOSYSFSTYP
            {
                get { return "TIRESSTOSYSFSTYP"; }
            }

            public static string TIRESSTOZINSFLAG
            {
                get { return "TIRESSTOZINSFLAG"; }
            }

            public static string TIRESSTOZINS
            {
                get { return "TIRESSTOZINS"; }
            }

            public static string BSERVSYSFSTYP
            {
                get { return "BSERVSYSFSTYP"; }
            }

            public static string BSERVFLAG
            {
                get { return "BSERVFLAG"; }
            }

            public static string BSERVZINS
            {
                get { return "BSERVZINS"; }
            }

            public static string MAINTSYSFSTYP
            {
                get { return "MAINTSYSFSTYP"; }
            }

            public static string MAINTZINSFLAG
            {
                get { return "MAINTZINSFLAG"; }
            }

            public static string MAINTZINS
            {
                get { return "MAINTZINS"; }
            }

            public static string REPSYSFSTYP
            {
                get { return "REPSYSFSTYP"; }
            }

            public static string REPZINSFLAG
            {
                get { return "REPZINSFLAG"; }
            }

            public static string REPZINS
            {
                get { return "REPZINS"; }
            }

            public static string DELIVSYSFSTYP
            {
                get { return "DELIVSYSFSTYP"; }
            }

            public static string DELIVZINSFLAG
            {
                get { return "DELIVZINSFLAG"; }
            }

            public static string DELIVZINS
            {
                get { return "DELIVZINS"; }
            }

            public static string CARWSYSFSTYP
            {
                get { return "CARWSYSFSTYP"; }
            }

            public static string CARWZINSFLAG
            {
                get { return "CARWZINSFLAG"; }
            }

            public static string CARWZINS
            {
                get { return "CARWZINS"; }
            }

            public static string VIGSYSFSTYP
            {
                get { return "VIGSYSFSTYP"; }
            }

            public static string VIGZINSFLAG
            {
                get { return "VIGZINSFLAG"; }
            }

            public static string VIGZINS
            {
                get { return "VIGZINS"; }
            }

            public static string INSSYSFSTYP
            {
                get { return "INSSYSFSTYP"; }
            }

            public static string INSZINSFLAG
            {
                get { return "INSZINSFLAG"; }
            }

            public static string INSZINS
            {
                get { return "INSZINS"; }
            }

            public static string SYSFZNGR
            {
                get { return "SYSFZNGR"; }
            }

            public static string TAXPRICE
            {
                get { return "TAXPRICE"; }
            }

            public static string FAHRERBET
            {
                get { return "FAHRERBET"; }
            }

            public static string FAHRERBETP
            {
                get { return "FAHRERBETP"; }
            }

            public static string AVGFUELCONS
            {
                get { return "AVGFUELCONS"; }
            }

            public static string STIRESCODEV
            {
                get { return "STIRESCODEV"; }
            }

            public static string STIRESMODV
            {
                get { return "STIRESMODV"; }
            }

            public static string STIRESTEXTV
            {
                get { return "STIRESTEXTV"; }
            }

            public static string STIRESCOUNTV
            {
                get { return "STIRESCOUNTV"; }
            }

            public static string STIRESPRICEV
            {
                get { return "STIRESPRICEV"; }
            }

            public static string STIRESCODEH
            {
                get { return "STIRESCODEH"; }
            }

            public static string STIRESMODH
            {
                get { return "STIRESMODH"; }
            }

            public static string STIRESTEXTH
            {
                get { return "STIRESTEXTH"; }
            }

            public static string STIRESCOUNTH
            {
                get { return "STIRESCOUNTH"; }
            }

            public static string STIRESPRICEH
            {
                get { return "STIRESPRICEH"; }
            }

            public static string WHOLEWEELFLAG
            {
                get { return "WHOLEWEELFLAG"; }
            }

            public static string WTIRESCODEV
            {
                get { return "WTIRESCODEV"; }
            }

            public static string WTIRESMODV
            {
                get { return "WTIRESMODV"; }
            }

            public static string WTIRESTEXTV
            {
                get { return "WTIRESTEXTV"; }
            }

            public static string WTIRESCOUNTV
            {
                get { return "WTIRESCOUNTV"; }
            }

            public static string WTIRESPRICEV
            {
                get { return "WTIRESPRICEV"; }
            }

            public static string WTIRESCODEH
            {
                get { return "WTIRESCODEH"; }
            }

            public static string WTIRESMODH
            {
                get { return "WTIRESMODH"; }
            }

            public static string WTIRESTEXTH
            {
                get { return "WTIRESTEXTH"; }
            }

            public static string WTIRESCOUNTH
            {
                get { return "WTIRESCOUNTH"; }
            }

            public static string WTIRESPRICEH
            {
                get { return "WTIRESPRICEH"; }
            }

            public static string RIMSCODEV
            {
                get { return "RIMSCODEV"; }
            }

            public static string RIMSCOUNTV
            {
                get { return "RIMSCOUNTV"; }
            }

            public static string RIMSPRICEV
            {
                get { return "RIMSPRICEV"; }
            }

            public static string RIMSCODEH
            {
                get { return "RIMSCODEH"; }
            }

            public static string RIMSCOUNTH
            {
                get { return "RIMSCOUNTH"; }
            }

            public static string RIMSPRICEH
            {
                get { return "RIMSPRICEH"; }
            }

            public static string TIRESADDFLAG
            {
                get { return "TIRESADDFLAG"; }
            }

            public static string TIRESADDITION
            {
                get { return "TIRESADDITION"; }
            }

            public static string ANABMELDUNG
            {
                get { return "ANABMELDUNG"; }
            }

            public static string ANABMLDFLAG
            {
                get { return "ANABMLDFLAG"; }
            }

            public static string MGMGEB
            {
                get { return "MGMGEB"; }
            }

            public static string MGMGEBFLAG
            {
                get { return "MGMGEBFLAG"; }
            }

            public static string FUELPAUSCHFLAG
            {
                get { return "FUELPAUSCHFLAG"; }
            }

            public static string EXTRASPRICE
            {
                get { return "EXTRASPRICE"; }
            }

            public static string EXTRASFLAG
            {
                get { return "EXTRASFLAG"; }
            }

            public static string HPFLAG
            {
                get { return "HPFLAG"; }
            }

            public static string VKFLAG
            {
                get { return "VKFLAG"; }
            }

            public static string RECHTSCHUTZ
            {
                get { return "RECHTSCHUTZ"; }
            }

            public static string RECHTSCHUTZFLAG
            {
                get { return "RECHTSCHUTZFLAG"; }
            }

            public static string MOTORVS
            {
                get { return "MOTORVS"; }
            }

            public static string MOTORVSFLAG
            {
                get { return "MOTORVSFLAG"; }
            }

            public static string INSASSEN
            {
                get { return "INSASSEN"; }
            }

            public static string INSASSENFLAG
            {
                get { return "INSASSENFLAG"; }
            }

            public static string TIRESFIXFLAG
            {
                get { return "TIRESFIXFLAG"; }
            }

            public static string MAINTFIXFLAG
            {
                get { return "MAINTFIXFLAG"; }
            }

            public static string MEHRKM
            {
                get { return "MEHRKM"; }
            }

            public static string MEHRKMP
            {
                get { return "MEHRKMP"; }
            }

            public static string MINDERKM
            {
                get { return "MINDERKM"; }
            }

            public static string MINDERKMP
            {
                get { return "MINDERKMP"; }
            }

            public static string ANABBRUTTO
            {
                get { return "ANABBRUTTO"; }
            }

            public static string ANABUST
            {
                get { return "ANABUST"; }
            }

            public static string EXTRASBRUTTO
            {
                get { return "EXTRASBRUTTO"; }
            }

            public static string EXTRASUST
            {
                get { return "EXTRASUST"; }
            }

            public static string FUELBRUTTO
            {
                get { return "FUELBRUTTO"; }
            }

            public static string FUELUST
            {
                get { return "FUELUST"; }
            }

            public static string MAINTENANCEBRUTTO
            {
                get { return "MAINTENANCEBRUTTO"; }
            }

            public static string MAINTENANCEUST
            {
                get { return "MAINTENANCEUST"; }
            }

            public static string REPCARRATEUST
            {
                get { return "REPCARRATEUST"; }
            }

            public static string REPCARRATE
            {
                get { return "REPCARRATE"; }
            }

            public static string REPCARRATEBRUTTO
            {
                get { return "REPCARRATEBRUTTO"; }
            }

            public static string RIMPRICEHUST
            {
                get { return "RIMPRICEHUST"; }
            }

            public static string RIMPRICEVBRUTTO
            {
                get { return "RIMPRICEVBRUTTO"; }
            }

            public static string RIMPRICEVUST
            {
                get { return "RIMPRICEVUST"; }
            }

            public static string STIRESPRICEHBRUTTO
            {
                get { return "STIRESPRICEHBRUTTO"; }
            }

            public static string STIRESPRICEHUST
            {
                get { return "STIRESPRICEHUST"; }
            }

            public static string STIRESPRICEVBRUTTO
            {
                get { return "STIRESPRICEVBRUTTO"; }
            }

            public static string STIRESPRICEVUST
            {
                get { return "STIRESPRICEVUST"; }
            }

            public static string TIRESADDITIONBRUTTO
            {
                get { return "TIRESADDITIONBRUTTO"; }
            }

            public static string TIRESADDITIONUST
            {
                get { return "TIRESADDITIONUST"; }
            }

            public static string WTIRESPRICEHBRUTTO
            {
                get { return "WTIRESPRICEHBRUTTO"; }
            }

            public static string WTIRESPRICEHUST
            {
                get { return "WTIRESPRICEHUST"; }
            }

            public static string WTIRESPRICEVUST
            {
                get { return "WTIRESPRICEVUST"; }
            }

            public static string WTIRESPRICEVBRUTTO
            {
                get { return "WTIRESPRICEVBRUTTO"; }
            }

            public static string TIRESSETS
            {
                get { return "TIRESSETS"; }
            }

            public static string ANABKENNZINKLFLAG
            {
                get { return "ANABKENNZINKLFLAG"; }
            }

            public static string RIMSMODH
            {
                get { return "RIMSMODH"; }
            }

            public static string RIMSMODV
            {
                get { return "RIMSMODV"; }
            }

            public static string RIMSPRICEHBRUTTO
            {
                get { return "RIMSPRICEHBRUTTO"; }
            }

            public static string RIMSPRICEHUST
            {
                get { return "RIMSPRICEHUST"; }
            }

            public static string RIMSPRICEVBRUTTO
            {
                get { return "RIMSPRICEVBRUTTO"; }
            }

            public static string RIMSPRICEVUST
            {
                get { return "RIMSPRICEVUST"; }
            }

            public static string STIRESPRICEBRUTTO
            {
                get { return "STIRESPRICEBRUTTO"; }
            }

            public static string STIRESPRICEUST
            {
                get { return "STIRESPRICEUST"; }
            }

            public static string TIRESINCLFLAG
            {
                get { return "TIRESINCLFLAG"; }
            }

            public static string MEHRKMBRUTTO
            {
                get { return "MEHRKMBRUTTO"; }
            }

            public static string MEHRKMUST
            {
                get { return "MEHRKMUST"; }
            }

            public static string MINDERKMBRUTTO
            {
                get { return "MINDERKMBRUTTO"; }
            }

            public static string MINDERKMUST
            {
                get { return "MINDERKMUST"; }
            }

            public static string FUELPRICEAVG
            {
                get { return "FUELPRICEAVG"; }
            }

            public static string FUELPRICEAVGUST
            {
                get { return "FUELPRICEAVGUST"; }
            }

            public static string FUELPRICEAVGBRUTTO
            {
                get { return "FUELPRICEAVGBRUTTO"; }
            }

            public static string VKSTUFE
            {
                get { return "VKSTUFE"; }
            }

            public static string HPSTUFE
            {
                get { return "HPSTUFE"; }
            }

            public static string HPDECKUNGSSUMME
            {
                get { return "HPDECKUNGSSUMME"; }
            }

            public static string HPBRUTTO
            {
                get { return "HPBRUTTO"; }
            }

            public static string HPVS
            {
                get { return "HPVS"; }
            }

            public static string HPNACHLASS
            {
                get { return "HPNACHLASS"; }
            }

            public static string VKBRUTTO
            {
                get { return "VKBRUTTO"; }
            }

            public static string VKNACHLASS
            {
                get { return "VKNACHLASS"; }
            }

            public static string VKVS
            {
                get { return "VKVS"; }
            }

            public static string RECHTSCHUTZBRUTTO
            {
                get { return "RECHTSCHUTZBRUTTO"; }
            }

            public static string RECHTSCHUTZVS
            {
                get { return "RECHTSCHUTZVS"; }
            }

            public static string RECHTSCHUTZNACHLASS
            {
                get { return "RECHTSCHUTZNACHLASS"; }
            }

            public static string SYSVSTYPRECHT
            {
                get { return "SYSVSTYPRECHT"; }
            }

            public static string SYSVSTYPHP
            {
                get { return "SYSVSTYPHP"; }
            }

            public static string SYSVSTYPVK
            {
                get { return "SYSVSTYPVK"; }
            }

            public static string SYSVSHPVOR
            {
                get { return "SYSVSHPVOR"; }
            }

            public static string SYSVSVKVOR
            {
                get { return "SYSVSVKVOR"; }
            }

            public static string SYSVSTYPINSASSEN
            {
                get { return "SYSVSTYPINSASSEN"; }
            }

            public static string INSASSENBRUTTO
            {
                get { return "INSASSENBRUTTO"; }
            }

            public static string INSASSENNACHLASS
            {
                get { return "INSASSENNACHLASS"; }
            }

            public static string RSVFLAG
            {
                get { return "RSVFLAG"; }
            }

            public static string SYSVSTYPRSV
            {
                get { return "SYSVSTYPRSV"; }
            }

            public static string RSV
            {
                get { return "RSV"; }
            }

            public static string RSVVS
            {
                get { return "RSVVS"; }
            }

            public static string SYSITRSVVN
            {
                get { return "SYSITRSVVN"; }
            }

            public static string SYSVARIANTEVK
            {
                get { return "SYSVARIANTEVK"; }
            }

            public static string VKZUBKUNDE
            {
                get { return "VKZUBKUNDE"; }
            }

            public static string ANABNACHLASS
            {
                get { return "ANABNACHLASS"; }
            }

            public static string FUELNACHLASS
            {
                get { return "FUELNACHLASS"; }
            }

            public static string MAINTNACHLASS
            {
                get { return "MAINTNACHLASS"; }
            }

            public static string TIRESNACHLASS
            {
                get { return "TIRESNACHLASS"; }
            }

            public static string REPCARNACHLASS
            {
                get { return "REPCARNACHLASS"; }
            }

            public static string EXTRASNACHLASS
            {
                get { return "EXTRASNACHLASS"; }
            }

            public static string ANABPRICE
            {
                get { return "ANABPRICE"; }
            }

            public static string ANABPRICEBRUTTO
            {
                get { return "ANABPRICEBRUTTO"; }
            }

            public static string MAINTPRICEKM
            {
                get { return "MAINTPRICEKM"; }
            }


			#endregion
        }

    }
}