// AUTOGENERATED, 18.11.2010 15:27:38
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ANGOBSICH
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ANGOBSICH));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSID
            {
                get { return "SYSID"; }
            }

            public static string SYSPERSON
            {
                get { return "SYSPERSON"; }
            }

            public static string SYSRAP
            {
                get { return "SYSRAP"; }
            }

            public static string SYSMH
            {
                get { return "SYSMH"; }
            }

            public static string RANG
            {
                get { return "RANG"; }
            }

            public static string TYP
            {
                get { return "TYP"; }
            }

            public static string STATUS
            {
                get { return "STATUS"; }
            }

            public static string STATUSDAT
            {
                get { return "STATUSDAT"; }
            }

            public static string AKTIVFLAG
            {
                get { return "AKTIVFLAG"; }
            }

            public static string SCORE
            {
                get { return "SCORE"; }
            }

            public static string OBLIGOFLAG
            {
                get { return "OBLIGOFLAG"; }
            }

            public static string BEZEICHNUNG
            {
                get { return "BEZEICHNUNG"; }
            }

            public static string GEGENSTAND
            {
                get { return "GEGENSTAND"; }
            }

            public static string AK
            {
                get { return "AK"; }
            }

            public static string WERT
            {
                get { return "WERT"; }
            }

            public static string SYSWAEHRUNG
            {
                get { return "SYSWAEHRUNG"; }
            }

            public static string BEGINN
            {
                get { return "BEGINN"; }
            }

            public static string STAND
            {
                get { return "STAND"; }
            }

            public static string ENDE
            {
                get { return "ENDE"; }
            }

            public static string KAUTION
            {
                get { return "KAUTION"; }
            }

            public static string BEGINNKAUTION
            {
                get { return "BEGINNKAUTION"; }
            }

            public static string STANDKAUTION
            {
                get { return "STANDKAUTION"; }
            }

            public static string ZINS
            {
                get { return "ZINS"; }
            }

            public static string PERIODE
            {
                get { return "PERIODE"; }
            }

            public static string BRUTTOKAUTION
            {
                get { return "BRUTTOKAUTION"; }
            }

            public static string OPTION1
            {
                get { return "OPTION1"; }
            }

            public static string OPTION2
            {
                get { return "OPTION2"; }
            }

            public static string OPTION3
            {
                get { return "OPTION3"; }
            }

            public static string OPTION4
            {
                get { return "OPTION4"; }
            }

            public static string OPTION5
            {
                get { return "OPTION5"; }
            }

            public static string OPTION6
            {
                get { return "OPTION6"; }
            }

            public static string OPTION7
            {
                get { return "OPTION7"; }
            }

            public static string OPTION8
            {
                get { return "OPTION8"; }
            }

            public static string OPTION9
            {
                get { return "OPTION9"; }
            }

            public static string OPTION10
            {
                get { return "OPTION10"; }
            }

            public static string SYSNKONTO
            {
                get { return "SYSNKONTO"; }
            }

            public static string SBBETRAG
            {
                get { return "SBBETRAG"; }
            }

            public static string SBPROZENT
            {
                get { return "SBPROZENT"; }
            }

            public static string FLAG01
            {
                get { return "FLAG01"; }
            }

            public static string FLAG02
            {
                get { return "FLAG02"; }
            }

            public static string FLAG03
            {
                get { return "FLAG03"; }
            }

            public static string FLAG04
            {
                get { return "FLAG04"; }
            }

            public static string FLAG05
            {
                get { return "FLAG05"; }
            }

            public static string FLAG06
            {
                get { return "FLAG06"; }
            }

            public static string FLAG07
            {
                get { return "FLAG07"; }
            }

            public static string FLAG08
            {
                get { return "FLAG08"; }
            }

            public static string FLAG09
            {
                get { return "FLAG09"; }
            }

            public static string FLAG10
            {
                get { return "FLAG10"; }
            }


			#endregion
        }

    }
}