// AUTOGENERATED, 18.11.2010 15:27:38
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ANTOB
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ANTOB));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSOB
            {
                get { return "SYSOB"; }
            }

            public static string OBJEKT
            {
                get { return "OBJEKT"; }
            }

            public static string RANG
            {
                get { return "RANG"; }
            }

            public static string ERSTELLUNG
            {
                get { return "ERSTELLUNG"; }
            }

            public static string BEARBEITUNG
            {
                get { return "BEARBEITUNG"; }
            }

            public static string OK
            {
                get { return "OK"; }
            }

            public static string AKTIVKZ
            {
                get { return "AKTIVKZ"; }
            }

            public static string LIEFERUNG
            {
                get { return "LIEFERUNG"; }
            }

            public static string BEZEICHNUNG
            {
                get { return "BEZEICHNUNG"; }
            }

            public static string FABRIKAT
            {
                get { return "FABRIKAT"; }
            }

            public static string KENNZEICHEN
            {
                get { return "KENNZEICHEN"; }
            }

            public static string OBJEKTZUSTAND
            {
                get { return "OBJEKTZUSTAND"; }
            }

            public static string FZART
            {
                get { return "FZART"; }
            }

            public static string SERIE
            {
                get { return "SERIE"; }
            }

            public static string HERSTELLER
            {
                get { return "HERSTELLER"; }
            }

            public static string BAUJAHR
            {
                get { return "BAUJAHR"; }
            }

            public static string ABNAHMEKM
            {
                get { return "ABNAHMEKM"; }
            }

            public static string JAHRESKM
            {
                get { return "JAHRESKM"; }
            }

            public static string KMTOLERANZ
            {
                get { return "KMTOLERANZ"; }
            }

            public static string SATZMEHRKM
            {
                get { return "SATZMEHRKM"; }
            }

            public static string SATZMINDERKM
            {
                get { return "SATZMINDERKM"; }
            }

            public static string GRUND
            {
                get { return "GRUND"; }
            }

            public static string GESAMT
            {
                get { return "GESAMT"; }
            }

            public static string BGEXTERN
            {
                get { return "BGEXTERN"; }
            }

            public static string SZ
            {
                get { return "SZ"; }
            }

            public static string RW
            {
                get { return "RW"; }
            }

            public static string NOVA
            {
                get { return "NOVA"; }
            }

            public static string SCHWACKE
            {
                get { return "SCHWACKE"; }
            }

            public static string FARBEI
            {
                get { return "FARBEI"; }
            }

            public static string FARBEA
            {
                get { return "FARBEA"; }
            }

            public static string AUTOMATIK
            {
                get { return "AUTOMATIK"; }
            }

            public static string ANZAHLTUEREN
            {
                get { return "ANZAHLTUEREN"; }
            }

            public static string ANZAHLSITZE
            {
                get { return "ANZAHLSITZE"; }
            }

            public static string PS
            {
                get { return "PS"; }
            }

            public static string KW
            {
                get { return "KW"; }
            }

            public static string CCM
            {
                get { return "CCM"; }
            }

            public static string FAHRER
            {
                get { return "FAHRER"; }
            }

            public static string SYSLS
            {
                get { return "SYSLS"; }
            }

            public static string BESCHRENGLISCH
            {
                get { return "BESCHRENGLISCH"; }
            }

            public static string ZYLINDER
            {
                get { return "ZYLINDER"; }
            }

            public static string TYP
            {
                get { return "TYP"; }
            }

            public static string FGNR
            {
                get { return "FGNR"; }
            }

            public static string FZNR
            {
                get { return "FZNR"; }
            }

            public static string ZUBEHOER
            {
                get { return "ZUBEHOER"; }
            }

            public static string NOVAP
            {
                get { return "NOVAP"; }
            }

            public static string NOVAZUAB
            {
                get { return "NOVAZUAB"; }
            }

            public static string RWCRV
            {
                get { return "RWCRV"; }
            }


			#endregion
        }

    }
}