// AUTOGENERATED, 18.11.2010 15:27:39
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ANTOPTION
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ANTOPTION));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSID
            {
                get { return "SYSID"; }
            }

            public static string OPTION1
            {
                get { return "OPTION1"; }
            }

            public static string OPTION2
            {
                get { return "OPTION2"; }
            }

            public static string OPTION3
            {
                get { return "OPTION3"; }
            }

            public static string OPTION4
            {
                get { return "OPTION4"; }
            }

            public static string OPTION5
            {
                get { return "OPTION5"; }
            }

            public static string OPTION6
            {
                get { return "OPTION6"; }
            }

            public static string OPTION7
            {
                get { return "OPTION7"; }
            }

            public static string OPTION8
            {
                get { return "OPTION8"; }
            }

            public static string OPTION9
            {
                get { return "OPTION9"; }
            }

            public static string OPTION10
            {
                get { return "OPTION10"; }
            }

            public static string OPTION11
            {
                get { return "OPTION11"; }
            }

            public static string OPTION12
            {
                get { return "OPTION12"; }
            }

            public static string OPTION13
            {
                get { return "OPTION13"; }
            }

            public static string OPTION14
            {
                get { return "OPTION14"; }
            }

            public static string OPTION15
            {
                get { return "OPTION15"; }
            }

            public static string OPTION16
            {
                get { return "OPTION16"; }
            }

            public static string OPTION17
            {
                get { return "OPTION17"; }
            }

            public static string OPTION18
            {
                get { return "OPTION18"; }
            }

            public static string OPTION19
            {
                get { return "OPTION19"; }
            }

            public static string OPTION20
            {
                get { return "OPTION20"; }
            }


			#endregion
        }

    }
}