// AUTOGENERATED, 18.11.2010 15:27:36
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class APPROVAL
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(APPROVAL));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSAPPROVAL
            {
                get { return "SYSAPPROVAL"; }
            }

            public static string VOTUM
            {
                get { return "VOTUM"; }
            }

            public static string VOTUMREM
            {
                get { return "VOTUMREM"; }
            }

            public static string VOTUMKOMP
            {
                get { return "VOTUMKOMP"; }
            }

            public static string VOTUMDATUM
            {
                get { return "VOTUMDATUM"; }
            }

            public static string GENEHMIGUNG
            {
                get { return "GENEHMIGUNG"; }
            }

            public static string GENEHMREM
            {
                get { return "GENEHMREM"; }
            }

            public static string AUFLAGENREM
            {
                get { return "AUFLAGENREM"; }
            }

            public static string AUFLAGENKOMP
            {
                get { return "AUFLAGENKOMP"; }
            }

            public static string AUFLAGENDATUM
            {
                get { return "AUFLAGENDATUM"; }
            }

            public static string SICHERHEITEN
            {
                get { return "SICHERHEITEN"; }
            }

            public static string KALKULATION
            {
                get { return "KALKULATION"; }
            }


			#endregion
        }

    }
}