// AUTOGENERATED, 18.11.2010 15:27:39
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class FSTYP
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(FSTYP));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSFSTYP
            {
                get { return "SYSFSTYP"; }
            }

            public static string BEZEICHNUNG
            {
                get { return "BEZEICHNUNG"; }
            }

            public static string BESCHREIBUNG
            {
                get { return "BESCHREIBUNG"; }
            }

            public static string ZINSFLAG
            {
                get { return "ZINSFLAG"; }
            }

            public static string ZINS
            {
                get { return "ZINS"; }
            }

            public static string SYSFSART
            {
                get { return "SYSFSART"; }
            }

            public static string SYSFS
            {
                get { return "SYSFS"; }
            }

            public static string FIXVAROPTION
            {
                get { return "FIXVAROPTION"; }
            }

            public static string FIXVARDEFAULT
            {
                get { return "FIXVARDEFAULT"; }
            }

            public static string METHOD
            {
                get { return "METHOD"; }
            }

            public static string SYSVG
            {
                get { return "SYSVG"; }
            }


			#endregion
        }

    }
}