// AUTOGENERATED, 18.11.2010 15:27:37
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class KREMO
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(KREMO));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSKREMO
            {
                get { return "SYSKREMO"; }
            }

            public static string SYSPERSON
            {
                get { return "SYSPERSON"; }
            }

            public static string SYSKREMOP
            {
                get { return "SYSKREMOP"; }
            }

            public static string SYSVT
            {
                get { return "SYSVT"; }
            }

            public static string SYSANTRAG
            {
                get { return "SYSANTRAG"; }
            }

            public static string SYSANGEBOT
            {
                get { return "SYSANGEBOT"; }
            }

            public static string ANFRAGEDATUM
            {
                get { return "ANFRAGEDATUM"; }
            }

            public static string ANFRAGEUSER
            {
                get { return "ANFRAGEUSER"; }
            }

            public static string RANG
            {
                get { return "RANG"; }
            }

            public static string PARTNERFLAG
            {
                get { return "PARTNERFLAG"; }
            }

            public static string GEBDATUM
            {
                get { return "GEBDATUM"; }
            }

            public static string ANREDECODE
            {
                get { return "ANREDECODE"; }
            }

            public static string KALKCODE
            {
                get { return "KALKCODE"; }
            }

            public static string GLZ
            {
                get { return "GLZ"; }
            }

            public static string KREDITSUMME
            {
                get { return "KREDITSUMME"; }
            }

            public static string RW
            {
                get { return "RW"; }
            }

            public static string ZINS
            {
                get { return "ZINS"; }
            }

            public static string ZINSNOMFLAG
            {
                get { return "ZINSNOMFLAG"; }
            }

            public static string EINKBRUTTO
            {
                get { return "EINKBRUTTO"; }
            }

            public static string EINKNETTO
            {
                get { return "EINKNETTO"; }
            }

            public static string ERSATZ
            {
                get { return "ERSATZ"; }
            }

            public static string FAMSTANDCODE
            {
                get { return "FAMSTANDCODE"; }
            }

            public static string GRUNDCODE
            {
                get { return "GRUNDCODE"; }
            }

            public static string KANTONCODE
            {
                get { return "KANTONCODE"; }
            }

            public static string ANZKIND1
            {
                get { return "ANZKIND1"; }
            }

            public static string ANZKIND2
            {
                get { return "ANZKIND2"; }
            }

            public static string ANZKIND3
            {
                get { return "ANZKIND3"; }
            }

            public static string KIRCHSTFLAG
            {
                get { return "KIRCHSTFLAG"; }
            }

            public static string KREDRATE1
            {
                get { return "KREDRATE1"; }
            }

            public static string KREDENDEDAT1
            {
                get { return "KREDENDEDAT1"; }
            }

            public static string KREDRATE2
            {
                get { return "KREDRATE2"; }
            }

            public static string KREDENDEDAT2
            {
                get { return "KREDENDEDAT2"; }
            }

            public static string KREDRATE3
            {
                get { return "KREDRATE3"; }
            }

            public static string KREDENDEDAT3
            {
                get { return "KREDENDEDAT3"; }
            }

            public static string KREDRATE4
            {
                get { return "KREDRATE4"; }
            }

            public static string KREDENDEDAT4
            {
                get { return "KREDENDEDAT4"; }
            }

            public static string LEASINGRATE
            {
                get { return "LEASINGRATE"; }
            }

            public static string MIETE
            {
                get { return "MIETE"; }
            }

            public static string NEBEINKNETTO
            {
                get { return "NEBEINKNETTO"; }
            }

            public static string PLZ
            {
                get { return "PLZ"; }
            }

            public static string AUSLAGEN
            {
                get { return "AUSLAGEN"; }
            }

            public static string UNTERHALT
            {
                get { return "UNTERHALT"; }
            }

            public static string ZUSAUSL1
            {
                get { return "ZUSAUSL1"; }
            }

            public static string ZUSAUSL2
            {
                get { return "ZUSAUSL2"; }
            }

            public static string ZUSAUSL3
            {
                get { return "ZUSAUSL3"; }
            }

            public static string ZUSAUSL4
            {
                get { return "ZUSAUSL4"; }
            }

            public static string RATEBERECHNET
            {
                get { return "RATEBERECHNET"; }
            }

            public static string QSTFLAG
            {
                get { return "QSTFLAG"; }
            }

            public static string NEBEINKBRUTTO
            {
                get { return "NEBEINKBRUTTO"; }
            }

            public static string EINKBRUTTOBERECH
            {
                get { return "EINKBRUTTOBERECH"; }
            }

            public static string EX
            {
                get { return "EX"; }
            }

            public static string EX36
            {
                get { return "EX36"; }
            }

            public static string EXKORR
            {
                get { return "EXKORR"; }
            }

            public static string EXKORR36
            {
                get { return "EXKORR36"; }
            }

            public static string EXTOT
            {
                get { return "EXTOT"; }
            }

            public static string EXTOT36
            {
                get { return "EXTOT36"; }
            }

            public static string GRUNDBETRAG
            {
                get { return "GRUNDBETRAG"; }
            }

            public static string BETRKIND1
            {
                get { return "BETRKIND1"; }
            }

            public static string BETRKIND2
            {
                get { return "BETRKIND2"; }
            }

            public static string BETRKIND3
            {
                get { return "BETRKIND3"; }
            }

            public static string BETRKREDIT
            {
                get { return "BETRKREDIT"; }
            }

            public static string BETRKREDIT36
            {
                get { return "BETRKREDIT36"; }
            }

            public static string BETRLEASING
            {
                get { return "BETRLEASING"; }
            }

            public static string RATEBERECHNEU
            {
                get { return "RATEBERECHNEU"; }
            }

            public static string RATEBERECHNEU36
            {
                get { return "RATEBERECHNEU36"; }
            }

            public static string SALDO
            {
                get { return "SALDO"; }
            }

            public static string SALDO36
            {
                get { return "SALDO36"; }
            }

            public static string SALDOKORR
            {
                get { return "SALDOKORR"; }
            }

            public static string SALDOKORR36
            {
                get { return "SALDOKORR36"; }
            }

            public static string SALDONEU
            {
                get { return "SALDONEU"; }
            }

            public static string SALDONEU36
            {
                get { return "SALDONEU36"; }
            }

            public static string SALDONEUKORR
            {
                get { return "SALDONEUKORR"; }
            }

            public static string SALDONEUKORR36
            {
                get { return "SALDONEUKORR36"; }
            }

            public static string SALDONEUTOT
            {
                get { return "SALDONEUTOT"; }
            }

            public static string SALDONEUTOT36
            {
                get { return "SALDONEUTOT36"; }
            }

            public static string SALDOTOT
            {
                get { return "SALDOTOT"; }
            }

            public static string SALDOTOT36
            {
                get { return "SALDOTOT36"; }
            }

            public static string SOZIALAUSL1
            {
                get { return "SOZIALAUSL1"; }
            }

            public static string SOZIALAUSL2
            {
                get { return "SOZIALAUSL2"; }
            }

            public static string STEUERN
            {
                get { return "STEUERN"; }
            }

            public static string QUOTE
            {
                get { return "QUOTE"; }
            }

            public static string ZINSEFF
            {
                get { return "ZINSEFF"; }
            }

            public static string AUSBERECHN1
            {
                get { return "AUSBERECHN1"; }
            }

            public static string AUSBERECHN2
            {
                get { return "AUSBERECHN2"; }
            }

            public static string AUSBERECHN3
            {
                get { return "AUSBERECHN3"; }
            }

            public static string AUSBERECHN4
            {
                get { return "AUSBERECHN4"; }
            }

            public static string RATEEFF
            {
                get { return "RATEEFF"; }
            }

            public static string NEBEINKBRUTTOBERECH
            {
                get { return "NEBEINKBRUTTOBERECH"; }
            }

            public static string FEHLERCODE
            {
                get { return "FEHLERCODE"; }
            }

            public static string NOTIZ
            {
                get { return "NOTIZ"; }
            }

            public static string VERSION
            {
                get { return "VERSION"; }
            }

            public static string KRANKENKASSE
            {
                get { return "KRANKENKASSE"; }
            }

            public static string ANREDECODE2
            {
                get { return "ANREDECODE2"; }
            }

            public static string GEBDATUM2
            {
                get { return "GEBDATUM2"; }
            }

            public static string EINKBRUTTO2
            {
                get { return "EINKBRUTTO2"; }
            }

            public static string EINKNETTO2
            {
                get { return "EINKNETTO2"; }
            }

            public static string FAMSTANDCODE2
            {
                get { return "FAMSTANDCODE2"; }
            }

            public static string KANTONCODE2
            {
                get { return "KANTONCODE2"; }
            }

            public static string KIRCHSTFLAG2
            {
                get { return "KIRCHSTFLAG2"; }
            }

            public static string KREDRATE12
            {
                get { return "KREDRATE12"; }
            }

            public static string KREDENDEDAT12
            {
                get { return "KREDENDEDAT12"; }
            }

            public static string KREDRATE22
            {
                get { return "KREDRATE22"; }
            }

            public static string KREDENDEDAT22
            {
                get { return "KREDENDEDAT22"; }
            }

            public static string KREDRATE32
            {
                get { return "KREDRATE32"; }
            }

            public static string KREDENDEDAT32
            {
                get { return "KREDENDEDAT32"; }
            }

            public static string KREDRATE42
            {
                get { return "KREDRATE42"; }
            }

            public static string KREDENDEDAT42
            {
                get { return "KREDENDEDAT42"; }
            }

            public static string LEASINGRATE2
            {
                get { return "LEASINGRATE2"; }
            }

            public static string NEBEINKNETTO2
            {
                get { return "NEBEINKNETTO2"; }
            }

            public static string NEBEINKBRUTTO2
            {
                get { return "NEBEINKBRUTTO2"; }
            }

            public static string PLZ2
            {
                get { return "PLZ2"; }
            }

            public static string AUSLAGEN2
            {
                get { return "AUSLAGEN2"; }
            }

            public static string UNTERHALT2
            {
                get { return "UNTERHALT2"; }
            }

            public static string ZUSAUSL12
            {
                get { return "ZUSAUSL12"; }
            }

            public static string ZUSAUSL22
            {
                get { return "ZUSAUSL22"; }
            }

            public static string ZUSAUSL32
            {
                get { return "ZUSAUSL32"; }
            }

            public static string ZUSAUSL42
            {
                get { return "ZUSAUSL42"; }
            }

            public static string QSTFLAG2
            {
                get { return "QSTFLAG2"; }
            }

            public static string ERSTERATE
            {
                get { return "ERSTERATE"; }
            }

            public static string STEUERCODE
            {
                get { return "STEUERCODE"; }
            }

            public static string BETRLEASING36
            {
                get { return "BETRLEASING36"; }
            }

            public static string BERECHKANTONCODE
            {
                get { return "BERECHKANTONCODE"; }
            }

            public static string BERECHKRANKENKASSE
            {
                get { return "BERECHKRANKENKASSE"; }
            }

            public static string EINKBRUTTOBERECH2
            {
                get { return "EINKBRUTTOBERECH2"; }
            }

            public static string NEBEINKBRUTTOBERECH2
            {
                get { return "NEBEINKBRUTTOBERECH2"; }
            }

            public static string EX2
            {
                get { return "EX2"; }
            }

            public static string EX362
            {
                get { return "EX362"; }
            }

            public static string EXKORR2
            {
                get { return "EXKORR2"; }
            }

            public static string EXKORR362
            {
                get { return "EXKORR362"; }
            }

            public static string BETRKREDIT2
            {
                get { return "BETRKREDIT2"; }
            }

            public static string BETRKREDIT362
            {
                get { return "BETRKREDIT362"; }
            }

            public static string BETRLEASING2
            {
                get { return "BETRLEASING2"; }
            }

            public static string BETRLEASING362
            {
                get { return "BETRLEASING362"; }
            }

            public static string SALDO2
            {
                get { return "SALDO2"; }
            }

            public static string SALDO362
            {
                get { return "SALDO362"; }
            }

            public static string SALDOKORR2
            {
                get { return "SALDOKORR2"; }
            }

            public static string SALDOKORR362
            {
                get { return "SALDOKORR362"; }
            }

            public static string SOZIALAUSL12
            {
                get { return "SOZIALAUSL12"; }
            }

            public static string STEUERN2
            {
                get { return "STEUERN2"; }
            }

            public static string AUSBERECHN12
            {
                get { return "AUSBERECHN12"; }
            }

            public static string AUSBERECHN22
            {
                get { return "AUSBERECHN22"; }
            }

            public static string AUSBERECHN32
            {
                get { return "AUSBERECHN32"; }
            }

            public static string AUSBERECHN42
            {
                get { return "AUSBERECHN42"; }
            }

            public static string BERECHKANTONCODE2
            {
                get { return "BERECHKANTONCODE2"; }
            }

            public static string SYSIT
            {
                get { return "SYSIT"; }
            }

            public static string SYSWFUSER
            {
                get { return "SYSWFUSER"; }
            }

            public static string PROCESSCODE
            {
                get { return "PROCESSCODE"; }
            }

            public static string REQUESTDATE
            {
                get { return "REQUESTDATE"; }
            }

            public static string REQUESTTIME
            {
                get { return "REQUESTTIME"; }
            }

            public static string REQUESTUSER
            {
                get { return "REQUESTUSER"; }
            }

            public static string RESPONSEDATE
            {
                get { return "RESPONSEDATE"; }
            }

            public static string RESPONSETIME
            {
                get { return "RESPONSETIME"; }
            }

            public static string ERRCODE
            {
                get { return "ERRCODE"; }
            }

            public static string ERRNUMBER
            {
                get { return "ERRNUMBER"; }
            }

            public static string ERRMESSAGE
            {
                get { return "ERRMESSAGE"; }
            }

            public static string HSNR
            {
                get { return "HSNR"; }
            }

            public static string NAME
            {
                get { return "NAME"; }
            }

            public static string VORNAME
            {
                get { return "VORNAME"; }
            }

            public static string ORT
            {
                get { return "ORT"; }
            }

            public static string STRASSE
            {
                get { return "STRASSE"; }
            }

            public static string ANREDE
            {
                get { return "ANREDE"; }
            }

            public static string FAMILIENSTAND
            {
                get { return "FAMILIENSTAND"; }
            }

            public static string HSNR2
            {
                get { return "HSNR2"; }
            }

            public static string NAME2
            {
                get { return "NAME2"; }
            }

            public static string VORNAME2
            {
                get { return "VORNAME2"; }
            }

            public static string ORT2
            {
                get { return "ORT2"; }
            }

            public static string STRASSE2
            {
                get { return "STRASSE2"; }
            }

            public static string MATCHID
            {
                get { return "MATCHID"; }
            }

            public static string KALKART
            {
                get { return "KALKART"; }
            }

            public static string FININSTCODE
            {
                get { return "FININSTCODE"; }
            }

            public static string GEBUEHRWIEDERK
            {
                get { return "GEBUEHRWIEDERK"; }
            }

            public static string GEBUEHREINMAL
            {
                get { return "GEBUEHREINMAL"; }
            }

            public static string GRUND
            {
                get { return "GRUND"; }
            }

            public static string HAENDLERCODE
            {
                get { return "HAENDLERCODE"; }
            }

            public static string KANTON
            {
                get { return "KANTON"; }
            }

            public static string SYSTEMCODE
            {
                get { return "SYSTEMCODE"; }
            }

            public static string ERSTERATEBERECH
            {
                get { return "ERSTERATEBERECH"; }
            }

            public static string KANTONCODEBERECH
            {
                get { return "KANTONCODEBERECH"; }
            }

            public static string MWSTAUFZINSZUSCHLAG
            {
                get { return "MWSTAUFZINSZUSCHLAG"; }
            }

            public static string ZINSZUSCHLAG
            {
                get { return "ZINSZUSCHLAG"; }
            }

            public static string KANTONCODEBERECH2
            {
                get { return "KANTONCODEBERECH2"; }
            }

            public static string MIETEBERECH
            {
                get { return "MIETEBERECH"; }
            }

            public static string UNTERHALTBERECH
            {
                get { return "UNTERHALTBERECH"; }
            }

            public static string AUSLAGENBERECH
            {
                get { return "AUSLAGENBERECH"; }
            }

            public static string AUSLAGENBERECH2
            {
                get { return "AUSLAGENBERECH2"; }
            }

            public static string ERSATZBERECH
            {
                get { return "ERSATZBERECH"; }
            }

            public static string ANRRUECKBERECH
            {
                get { return "ANRRUECKBERECH"; }
            }

            public static string ANREDE2
            {
                get { return "ANREDE2"; }
            }

            public static string FAMILIENSTAND2
            {
                get { return "FAMILIENSTAND2"; }
            }

            public static string SYSIT2
            {
                get { return "SYSIT2"; }
            }

            public static string SYSPERSON2
            {
                get { return "SYSPERSON2"; }
            }

            public static string EINKNETTOFLAG
            {
                get { return "EINKNETTOFLAG"; }
            }

            public static string EINKNETTOFLAG2
            {
                get { return "EINKNETTOFLAG2"; }
            }

            public static string SYSWFEXEC
            {
                get { return "SYSWFEXEC"; }
            }


			#endregion
        }

    }
}