// AUTOGENERATED, 18.11.2010 15:27:37
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class LAND
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(LAND));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSLAND
            {
                get { return "SYSLAND"; }
            }

            public static string ISO
            {
                get { return "ISO"; }
            }

            public static string KENNZEICHEN
            {
                get { return "KENNZEICHEN"; }
            }

            public static string EG
            {
                get { return "EG"; }
            }

            public static string COUNTRYNAME
            {
                get { return "COUNTRYNAME"; }
            }

            public static string FLAGS
            {
                get { return "FLAGS"; }
            }

            public static string DEFAULTFLAG
            {
                get { return "DEFAULTFLAG"; }
            }

            public static string BESTFIVEFLAG
            {
                get { return "BESTFIVEFLAG"; }
            }

            public static string NOTADDRESSRELEVANT
            {
                get { return "NOTADDRESSRELEVANT"; }
            }


			#endregion
        }

    }
}