// AUTOGENERATED, 18.11.2010 15:27:37
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class MWST
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(MWST));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSMWST
            {
                get { return "SYSMWST"; }
            }

            public static string PROZENT
            {
                get { return "PROZENT"; }
            }

            public static string ART
            {
                get { return "ART"; }
            }

            public static string MWSTFIBU
            {
                get { return "MWSTFIBU"; }
            }

            public static string PROZENTNEU
            {
                get { return "PROZENTNEU"; }
            }

            public static string GUELTIGAB
            {
                get { return "GUELTIGAB"; }
            }

            public static string DUMMY
            {
                get { return "DUMMY"; }
            }

            public static string CODE
            {
                get { return "CODE"; }
            }

            public static string BESCHREIBUNG
            {
                get { return "BESCHREIBUNG"; }
            }

            public static string SYSMWSTSTORNO
            {
                get { return "SYSMWSTSTORNO"; }
            }

            public static string QUOTE
            {
                get { return "QUOTE"; }
            }

            public static string EVALSKONTO
            {
                get { return "EVALSKONTO"; }
            }


			#endregion
        }

    }
}