// AUTOGENERATED, 18.11.2010 15:27:36
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class OBINI
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(OBINI));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSOBINI
            {
                get { return "SYSOBINI"; }
            }

            public static string ERSTZUL
            {
                get { return "ERSTZUL"; }
            }

            public static string VORBESITZER
            {
                get { return "VORBESITZER"; }
            }

            public static string DEPOT
            {
                get { return "DEPOT"; }
            }

            public static string KMSTAND
            {
                get { return "KMSTAND"; }
            }

            public static string MOTORFUEL
            {
                get { return "MOTORFUEL"; }
            }


			#endregion
        }

    }
}