// AUTOGENERATED, 18.11.2010 15:27:37
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class PARTNER
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(PARTNER));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSPARTNER
            {
                get { return "SYSPARTNER"; }
            }

            public static string TITEL
            {
                get { return "TITEL"; }
            }

            public static string LASTNAME
            {
                get { return "LASTNAME"; }
            }

            public static string FIRSTNAME
            {
                get { return "FIRSTNAME"; }
            }

            public static string GESCHLECHT
            {
                get { return "GESCHLECHT"; }
            }

            public static string GEBDATUM
            {
                get { return "GEBDATUM"; }
            }

            public static string SALUTATION
            {
                get { return "SALUTATION"; }
            }

            public static string TELEFON
            {
                get { return "TELEFON"; }
            }

            public static string MOBIL
            {
                get { return "MOBIL"; }
            }

            public static string PRIVAT
            {
                get { return "PRIVAT"; }
            }

            public static string FAX
            {
                get { return "FAX"; }
            }

            public static string EMAIL
            {
                get { return "EMAIL"; }
            }

            public static string SYSSPRACHE
            {
                get { return "SYSSPRACHE"; }
            }

            public static string PLZ
            {
                get { return "PLZ"; }
            }

            public static string ORT
            {
                get { return "ORT"; }
            }

            public static string STRASSE
            {
                get { return "STRASSE"; }
            }

            public static string HSNR
            {
                get { return "HSNR"; }
            }

            public static string ANREDE
            {
                get { return "ANREDE"; }
            }

            public static string SYSLAND
            {
                get { return "SYSLAND"; }
            }

            public static string AKTIVKZ
            {
                get { return "AKTIVKZ"; }
            }

            public static string SYSSTAAT
            {
                get { return "SYSSTAAT"; }
            }

            public static string SYSCTLANG
            {
                get { return "SYSCTLANG"; }
            }


			#endregion
        }

    }
}