// AUTOGENERATED, 18.11.2010 15:27:37
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class PEINFOC
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(PEINFOC));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSPEINFOC
            {
                get { return "SYSPEINFOC"; }
            }

            public static string ENTRYDATE
            {
                get { return "ENTRYDATE"; }
            }

            public static string LASTVERDATE
            {
                get { return "LASTVERDATE"; }
            }

            public static string KNOWNSINCEDATE
            {
                get { return "KNOWNSINCEDATE"; }
            }

            public static string TRADEREGNUMBER
            {
                get { return "TRADEREGNUMBER"; }
            }

            public static string FOUNDINGDATE
            {
                get { return "FOUNDINGDATE"; }
            }

            public static string BRANCHCODE
            {
                get { return "BRANCHCODE"; }
            }

            public static string BRANCHDESC
            {
                get { return "BRANCHDESC"; }
            }

            public static string NUMBOFSHARES
            {
                get { return "NUMBOFSHARES"; }
            }

            public static string NUMBOFEMP
            {
                get { return "NUMBOFEMP"; }
            }

            public static string AUDITINGCOMP
            {
                get { return "AUDITINGCOMP"; }
            }

            public static string LASTSHABPUBTEXT
            {
                get { return "LASTSHABPUBTEXT"; }
            }

            public static string LASTSHABPUBDATE
            {
                get { return "LASTSHABPUBDATE"; }
            }

            public static string COMPSTATE
            {
                get { return "COMPSTATE"; }
            }

            public static string CAPITAL
            {
                get { return "CAPITAL"; }
            }

            public static string CAPITALPAYED
            {
                get { return "CAPITALPAYED"; }
            }

            public static string PURPOSE
            {
                get { return "PURPOSE"; }
            }

            public static string LEADSHIPSIZE
            {
                get { return "LEADSHIPSIZE"; }
            }

            public static string LEADSHIPSIZENEG
            {
                get { return "LEADSHIPSIZENEG"; }
            }

            public static string MANAGEMENTSIZE
            {
                get { return "MANAGEMENTSIZE"; }
            }


			#endregion
        }

    }
}