// AUTOGENERATED, 18.11.2010 15:27:36
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class PEINFOADR
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(PEINFOADR));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSPEINFOADR
            {
                get { return "SYSPEINFOADR"; }
            }

            public static string ADRTYPE
            {
                get { return "ADRTYPE"; }
            }

            public static string RECHTSFORM
            {
                get { return "RECHTSFORM"; }
            }

            public static string GESCHLECHT
            {
                get { return "GESCHLECHT"; }
            }

            public static string VORNAME
            {
                get { return "VORNAME"; }
            }

            public static string NAME
            {
                get { return "NAME"; }
            }

            public static string MAEDCHENNAME
            {
                get { return "MAEDCHENNAME"; }
            }

            public static string STRASSE
            {
                get { return "STRASSE"; }
            }

            public static string HSNR
            {
                get { return "HSNR"; }
            }

            public static string PLZ
            {
                get { return "PLZ"; }
            }

            public static string ORT
            {
                get { return "ORT"; }
            }

            public static string GEBDATUM
            {
                get { return "GEBDATUM"; }
            }

            public static string TELEFON
            {
                get { return "TELEFON"; }
            }

            public static string FAX
            {
                get { return "FAX"; }
            }

            public static string HANDY
            {
                get { return "HANDY"; }
            }

            public static string LANDISO3166A3
            {
                get { return "LANDISO3166A3"; }
            }


			#endregion
        }

    }
}