// AUTOGENERATED, 18.11.2010 15:27:38
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class PRSUBV
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(PRSUBV));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSPRSUBV
            {
                get { return "SYSPRSUBV"; }
            }

            public static string NAME
            {
                get { return "NAME"; }
            }

            public static string DESCRIPTION
            {
                get { return "DESCRIPTION"; }
            }

            public static string RANK
            {
                get { return "RANK"; }
            }

            public static string TRGTYPE
            {
                get { return "TRGTYPE"; }
            }

            public static string AREA
            {
                get { return "AREA"; }
            }

            public static string SYSPRFLDTRG
            {
                get { return "SYSPRFLDTRG"; }
            }

            public static string SYSPRFLDTGT
            {
                get { return "SYSPRFLDTGT"; }
            }

            public static string CALCMETHOD
            {
                get { return "CALCMETHOD"; }
            }

            public static string SHAREMETHOD
            {
                get { return "SHAREMETHOD"; }
            }

            public static string SUBVRATE
            {
                get { return "SUBVRATE"; }
            }

            public static string SUBVVAL
            {
                get { return "SUBVVAL"; }
            }

            public static string TERM
            {
                get { return "TERM"; }
            }


			#endregion
        }

    }
}