// AUTOGENERATED, 18.11.2010 15:27:38
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class REIFTYP
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(REIFTYP));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSREIFTYP
            {
                get { return "SYSREIFTYP"; }
            }

            public static string CODE
            {
                get { return "CODE"; }
            }

            public static string BESCHREIBUNG
            {
                get { return "BESCHREIBUNG"; }
            }

            public static string REIFENBREITE
            {
                get { return "REIFENBREITE"; }
            }

            public static string HBV
            {
                get { return "HBV"; }
            }

            public static string BAUART
            {
                get { return "BAUART"; }
            }

            public static string FD
            {
                get { return "FD"; }
            }

            public static string LI
            {
                get { return "LI"; }
            }

            public static string GSY
            {
                get { return "GSY"; }
            }

            public static string SONDERID
            {
                get { return "SONDERID"; }
            }

            public static string HERSTELLER
            {
                get { return "HERSTELLER"; }
            }

            public static string PROFIL
            {
                get { return "PROFIL"; }
            }

            public static string BEMERKUNG
            {
                get { return "BEMERKUNG"; }
            }

            public static string NETTO
            {
                get { return "NETTO"; }
            }


			#endregion
        }

    }
}