// AUTOGENERATED, 18.11.2010 15:27:38
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOl
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class VSTYP
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(VSTYP));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSVSTYP
            {
                get { return "SYSVSTYP"; }
            }

            public static string CODE
            {
                get { return "CODE"; }
            }

            public static string BESCHREIBUNG
            {
                get { return "BESCHREIBUNG"; }
            }

            public static string KLASSEHP
            {
                get { return "KLASSEHP"; }
            }

            public static string SFKHP
            {
                get { return "SFKHP"; }
            }

            public static string FLAGSBHP
            {
                get { return "FLAGSBHP"; }
            }

            public static string SBHP
            {
                get { return "SBHP"; }
            }

            public static string FLAGNB
            {
                get { return "FLAGNB"; }
            }

            public static string KLASSEVK
            {
                get { return "KLASSEVK"; }
            }

            public static string SFKVK
            {
                get { return "SFKVK"; }
            }

            public static string FLAGSBVK
            {
                get { return "FLAGSBVK"; }
            }

            public static string SBVK
            {
                get { return "SBVK"; }
            }

            public static string NB
            {
                get { return "NB"; }
            }

            public static string NBP
            {
                get { return "NBP"; }
            }

            public static string REGION
            {
                get { return "REGION"; }
            }

            public static string MAXVSL
            {
                get { return "MAXVSL"; }
            }

            public static string MAXVSLPS
            {
                get { return "MAXVSLPS"; }
            }

            public static string FLAGNEUWERT
            {
                get { return "FLAGNEUWERT"; }
            }

            public static string FLAGERSATZWG
            {
                get { return "FLAGERSATZWG"; }
            }

            public static string FLAGVERUNTR
            {
                get { return "FLAGVERUNTR"; }
            }

            public static string FLAGPARKSCHADEN
            {
                get { return "FLAGPARKSCHADEN"; }
            }

            public static string PARKSCHADEN
            {
                get { return "PARKSCHADEN"; }
            }

            public static string FLAGEFFEKTEN
            {
                get { return "FLAGEFFEKTEN"; }
            }

            public static string EFFEKTEN
            {
                get { return "EFFEKTEN"; }
            }

            public static string FLAGINSASSEN
            {
                get { return "FLAGINSASSEN"; }
            }

            public static string INSASSEN
            {
                get { return "INSASSEN"; }
            }

            public static string PRAEMIEHP
            {
                get { return "PRAEMIEHP"; }
            }

            public static string PRAEMIEVK
            {
                get { return "PRAEMIEVK"; }
            }

            public static string PRAEMIERS
            {
                get { return "PRAEMIERS"; }
            }

            public static string PRAEMIEIN
            {
                get { return "PRAEMIEIN"; }
            }

            public static string RS
            {
                get { return "RS"; }
            }

            public static string FLAGRS
            {
                get { return "FLAGRS"; }
            }

            public static string SYSKORRTYP1
            {
                get { return "SYSKORRTYP1"; }
            }

            public static string SYSKORRTYP2
            {
                get { return "SYSKORRTYP2"; }
            }

            public static string CODEMETHOD
            {
                get { return "CODEMETHOD"; }
            }

            public static string MAXLAUFZEIT
            {
                get { return "MAXLAUFZEIT"; }
            }

            public static string FLAGDEFAULT
            {
                get { return "FLAGDEFAULT"; }
            }

            public static string FLAGINKASSOART
            {
                get { return "FLAGINKASSOART"; }
            }

            public static string FLAGZUBINKL
            {
                get { return "FLAGZUBINKL"; }
            }

            public static string SAPRAEMIENFREI
            {
                get { return "SAPRAEMIENFREI"; }
            }

            public static string BEZEICHNUNG
            {
                get { return "BEZEICHNUNG"; }
            }

            public static string ACTIVEFLAG
            {
                get { return "ACTIVEFLAG"; }
            }

            public static string VALIDFROM
            {
                get { return "VALIDFROM"; }
            }

            public static string VALIDUNTIL
            {
                get { return "VALIDUNTIL"; }
            }


			#endregion
        }

    }
}