// AUTOGENERATED, 16.10.2009 12:05:17
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOw
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ARCJSQ
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ARCJSQ));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSARCJSQ
            {
                get { return "SYSARCJSQ"; }
            }

            public static string SYSJSQ
            {
                get { return "SYSJSQ"; }
            }

            public static string SYSGEBIET
            {
                get { return "SYSGEBIET"; }
            }

            public static string GEBIET
            {
                get { return "GEBIET"; }
            }

            public static string DESCRIPTION
            {
                get { return "DESCRIPTION"; }
            }

            public static string WAITDATE
            {
                get { return "WAITDATE"; }
            }

            public static string WAITTIME
            {
                get { return "WAITTIME"; }
            }

            public static string SUBMITDATE
            {
                get { return "SUBMITDATE"; }
            }

            public static string SUBMITTIME
            {
                get { return "SUBMITTIME"; }
            }

            public static string PRIORITAET
            {
                get { return "PRIORITAET"; }
            }

            public static string POSITION
            {
                get { return "POSITION"; }
            }

            public static string SYSJS
            {
                get { return "SYSJS"; }
            }

            public static string JOBSTATUS
            {
                get { return "JOBSTATUS"; }
            }

            public static string WIEDERHOLUNG
            {
                get { return "WIEDERHOLUNG"; }
            }

            public static string JOBKETTE
            {
                get { return "JOBKETTE"; }
            }

            public static string JOBDATE
            {
                get { return "JOBDATE"; }
            }

            public static string SYSWFJPLAN
            {
                get { return "SYSWFJPLAN"; }
            }

            public static string SYSJSESSION
            {
                get { return "SYSJSESSION"; }
            }

            public static string STARTDATE
            {
                get { return "STARTDATE"; }
            }

            public static string STARTTIME
            {
                get { return "STARTTIME"; }
            }

            public static string ENDDATE
            {
                get { return "ENDDATE"; }
            }

            public static string ENDTIME
            {
                get { return "ENDTIME"; }
            }


			#endregion
        }

    }
}