// AUTOGENERATED, 16.10.2009 12:05:17
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOw
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class CMBULK
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(CMBULK));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSCMBULK
            {
                get { return "SYSCMBULK"; }
            }

            public static string PROCESSCODE
            {
                get { return "PROCESSCODE"; }
            }

            public static string PARNAME
            {
                get { return "PARNAME"; }
            }

            public static string ADAPTERNAME
            {
                get { return "ADAPTERNAME"; }
            }

            public static string ADAPTERIDENTIFIER
            {
                get { return "ADAPTERIDENTIFIER"; }
            }

            public static string ADAPTERVERSION
            {
                get { return "ADAPTERVERSION"; }
            }

            public static string SERVICENAME
            {
                get { return "SERVICENAME"; }
            }

            public static string SERVICEVERSION
            {
                get { return "SERVICEVERSION"; }
            }

            public static string SERVICEURL
            {
                get { return "SERVICEURL"; }
            }

            public static string REQUESTIDENTIFIER
            {
                get { return "REQUESTIDENTIFIER"; }
            }

            public static string FIRSTREQUESTDATE
            {
                get { return "FIRSTREQUESTDATE"; }
            }

            public static string FIRSTREQUESTTIME
            {
                get { return "FIRSTREQUESTTIME"; }
            }

            public static string LASTREQUESTDATE
            {
                get { return "LASTREQUESTDATE"; }
            }

            public static string LASTREQUESTTIME
            {
                get { return "LASTREQUESTTIME"; }
            }

            public static string LASTRESPONSEDATE
            {
                get { return "LASTRESPONSEDATE"; }
            }

            public static string LASTRESPONSETIME
            {
                get { return "LASTRESPONSETIME"; }
            }

            public static string LASTERRORCODE
            {
                get { return "LASTERRORCODE"; }
            }

            public static string LASTERRORMESSAGE
            {
                get { return "LASTERRORMESSAGE"; }
            }

            public static string LASTERRORNUMBER
            {
                get { return "LASTERRORNUMBER"; }
            }

            public static string MESSAGECODE
            {
                get { return "MESSAGECODE"; }
            }

            public static string PROVIDERCODE
            {
                get { return "PROVIDERCODE"; }
            }

            public static string SERVICECODE
            {
                get { return "SERVICECODE"; }
            }

            public static string SENDATDATE
            {
                get { return "SENDATDATE"; }
            }

            public static string SENDATTIME
            {
                get { return "SENDATTIME"; }
            }

            public static string TIMEOUTDATE
            {
                get { return "TIMEOUTDATE"; }
            }

            public static string TIMEOUTTIME
            {
                get { return "TIMEOUTTIME"; }
            }


			#endregion
        }

    }
}