// AUTOGENERATED, 16.10.2009 12:05:17
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOw
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class EAIART
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(EAIART));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSEAIART
            {
                get { return "SYSEAIART"; }
            }

            public static string CODE
            {
                get { return "CODE"; }
            }

            public static string DESCRIPTION
            {
                get { return "DESCRIPTION"; }
            }

            public static string FILEFLAG
            {
                get { return "FILEFLAG"; }
            }

            public static string FIELDSPEC01
            {
                get { return "FIELDSPEC01"; }
            }

            public static string FIELDVALUE01
            {
                get { return "FIELDVALUE01"; }
            }

            public static string FIELDSPEC02
            {
                get { return "FIELDSPEC02"; }
            }

            public static string FIELDVALUE02
            {
                get { return "FIELDVALUE02"; }
            }

            public static string FIELDSPEC03
            {
                get { return "FIELDSPEC03"; }
            }

            public static string FIELDVALUE03
            {
                get { return "FIELDVALUE03"; }
            }

            public static string FIELDSPEC04
            {
                get { return "FIELDSPEC04"; }
            }

            public static string FIELDVALUE04
            {
                get { return "FIELDVALUE04"; }
            }

            public static string FIELDSPEC05
            {
                get { return "FIELDSPEC05"; }
            }

            public static string FIELDVALUE05
            {
                get { return "FIELDVALUE05"; }
            }

            public static string EVALEXPRESSION
            {
                get { return "EVALEXPRESSION"; }
            }

            public static string TRANSACTIONFLAG
            {
                get { return "TRANSACTIONFLAG"; }
            }


			#endregion
        }

    }
}