// AUTOGENERATED, 16.10.2009 12:05:17
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOw
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class JSESSION
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(JSESSION));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSJSESSION
            {
                get { return "SYSJSESSION"; }
            }

            public static string CODE
            {
                get { return "CODE"; }
            }

            public static string PCNAME
            {
                get { return "PCNAME"; }
            }

            public static string DESCRIPTION
            {
                get { return "DESCRIPTION"; }
            }

            public static string DATABASE
            {
                get { return "DATABASE"; }
            }

            public static string SERVERUSER
            {
                get { return "SERVERUSER"; }
            }

            public static string STARTDATE
            {
                get { return "STARTDATE"; }
            }

            public static string STARTTIME
            {
                get { return "STARTTIME"; }
            }

            public static string SESSIONSTATUS
            {
                get { return "SESSIONSTATUS"; }
            }

            public static string ENDDATE
            {
                get { return "ENDDATE"; }
            }

            public static string ENDTIME
            {
                get { return "ENDTIME"; }
            }

            public static string SESSIONCONTROL
            {
                get { return "SESSIONCONTROL"; }
            }

            public static string SERVERART
            {
                get { return "SERVERART"; }
            }

            public static string SYSACTIVEJS
            {
                get { return "SYSACTIVEJS"; }
            }

            public static string SYSCICLOG
            {
                get { return "SYSCICLOG"; }
            }


			#endregion
        }

    }
}