// AUTOGENERATED, 16.10.2009 12:05:18
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOw
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class WFJEXEC
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(WFJEXEC));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSWFJEXEC
            {
                get { return "SYSWFJEXEC"; }
            }

            public static string TABLESYSCODE
            {
                get { return "TABLESYSCODE"; }
            }

            public static string DATUM
            {
                get { return "DATUM"; }
            }

            public static string UHRZEIT
            {
                get { return "UHRZEIT"; }
            }

            public static string JOBTEXT
            {
                get { return "JOBTEXT"; }
            }

            public static string JOBDATE
            {
                get { return "JOBDATE"; }
            }

            public static string APPROXCOUNT
            {
                get { return "APPROXCOUNT"; }
            }

            public static string SYSCICLOG
            {
                get { return "SYSCICLOG"; }
            }

            public static string STATUS
            {
                get { return "STATUS"; }
            }


			#endregion
        }

    }
}