// AUTOGENERATED, 16.10.2009 12:05:17
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdOw
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class WFJPLAN
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(WFJPLAN));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string SYSWFJPLAN
            {
                get { return "SYSWFJPLAN"; }
            }

            public static string EXECDATE
            {
                get { return "EXECDATE"; }
            }

            public static string EXECTIME
            {
                get { return "EXECTIME"; }
            }

            public static string JOBDATE
            {
                get { return "JOBDATE"; }
            }

            public static string BESCHREIBUNG
            {
                get { return "BESCHREIBUNG"; }
            }

            public static string GEBIET
            {
                get { return "GEBIET"; }
            }

            public static string SYSGEBIET
            {
                get { return "SYSGEBIET"; }
            }

            public static string FLAGEXECUTED
            {
                get { return "FLAGEXECUTED"; }
            }

            public static string EXECUTEDDATE
            {
                get { return "EXECUTEDDATE"; }
            }

            public static string EXECUTEDTIME
            {
                get { return "EXECUTEDTIME"; }
            }

            public static string ESTIMATEDATE
            {
                get { return "ESTIMATEDATE"; }
            }

            public static string ESTIMATETIME
            {
                get { return "ESTIMATETIME"; }
            }


			#endregion
        }

    }
}