// AUTOGENERATED, 26.01.2010 17:01:13
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdEurotax
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ETGCONSUMER
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ETGCONSUMER));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string MARKET
            {
                get { return "MARKET"; }
            }

            public static string VEHTYPE
            {
                get { return "VEHTYPE"; }
            }

            public static string NATCODE
            {
                get { return "NATCODE"; }
            }

            public static string RECSTATUS
            {
                get { return "RECSTATUS"; }
            }

            public static string RECDATE
            {
                get { return "RECDATE"; }
            }

            public static string SERVINTDISP
            {
                get { return "SERVINTDISP"; }
            }

            public static string MANMI
            {
                get { return "MANMI"; }
            }

            public static string GUARMON
            {
                get { return "GUARMON"; }
            }

            public static string GUARDIST
            {
                get { return "GUARDIST"; }
            }

            public static string RUSTGMON
            {
                get { return "RUSTGMON"; }
            }

            public static string RUSTGDIST
            {
                get { return "RUSTGDIST"; }
            }

            public static string MOBGMON
            {
                get { return "MOBGMON"; }
            }

            public static string PAINTGMON
            {
                get { return "PAINTGMON"; }
            }

            public static string RUSTRG
            {
                get { return "RUSTRG"; }
            }

            public static string UNITOFDISTANCCD2
            {
                get { return "UNITOFDISTANCCD2"; }
            }

            public static string TOPSPEED
            {
                get { return "TOPSPEED"; }
            }

            public static string TOPSPEEDV2
            {
                get { return "TOPSPEEDV2"; }
            }

            public static string GEARTOPSPD
            {
                get { return "GEARTOPSPD"; }
            }

            public static string KMSTANDING
            {
                get { return "KMSTANDING"; }
            }

            public static string KMSTANDINGV2
            {
                get { return "KMSTANDINGV2"; }
            }

            public static string ACCEL
            {
                get { return "ACCEL"; }
            }

            public static string ACCELV2
            {
                get { return "ACCELV2"; }
            }

            public static string ELAST
            {
                get { return "ELAST"; }
            }

            public static string ELASTV2
            {
                get { return "ELASTV2"; }
            }

            public static string TANKRANGE
            {
                get { return "TANKRANGE"; }
            }

            public static string TANKRANGEV2
            {
                get { return "TANKRANGEV2"; }
            }

            public static string CONSURB
            {
                get { return "CONSURB"; }
            }

            public static string CONSURBV2
            {
                get { return "CONSURBV2"; }
            }

            public static string CONSLAND
            {
                get { return "CONSLAND"; }
            }

            public static string CONSLANDV2
            {
                get { return "CONSLANDV2"; }
            }

            public static string CONSTOT
            {
                get { return "CONSTOT"; }
            }

            public static string CONSTOTV2
            {
                get { return "CONSTOTV2"; }
            }

            public static string CONSO90
            {
                get { return "CONSO90"; }
            }

            public static string CONSO120
            {
                get { return "CONSO120"; }
            }

            public static string CONSOURB
            {
                get { return "CONSOURB"; }
            }

            public static string CONSOMIX
            {
                get { return "CONSOMIX"; }
            }

            public static string CONSO90V2
            {
                get { return "CONSO90V2"; }
            }

            public static string CONSO120V2
            {
                get { return "CONSO120V2"; }
            }

            public static string CONSOURBV2
            {
                get { return "CONSOURBV2"; }
            }

            public static string CONSOMIXV2
            {
                get { return "CONSOMIXV2"; }
            }

            public static string DRAGCW
            {
                get { return "DRAGCW"; }
            }

            public static string AREA
            {
                get { return "AREA"; }
            }

            public static string AREAMAX
            {
                get { return "AREAMAX"; }
            }

            public static string DRAGIND
            {
                get { return "DRAGIND"; }
            }

            public static string CO2EMI
            {
                get { return "CO2EMI"; }
            }

            public static string CO2EMIV2
            {
                get { return "CO2EMIV2"; }
            }

            public static string DRVNOISE
            {
                get { return "DRVNOISE"; }
            }

            public static string CO
            {
                get { return "CO"; }
            }

            public static string HC
            {
                get { return "HC"; }
            }

            public static string NOX
            {
                get { return "NOX"; }
            }

            public static string PART
            {
                get { return "PART"; }
            }

            public static string CONSPOW
            {
                get { return "CONSPOW"; }
            }

            public static string CONSPOWV2
            {
                get { return "CONSPOWV2"; }
            }

            public static string TXTBATTYPECD2
            {
                get { return "TXTBATTYPECD2"; }
            }

            public static string NUMBAT
            {
                get { return "NUMBAT"; }
            }

            public static string BATCAP
            {
                get { return "BATCAP"; }
            }

            public static string NUMCHARCYCL
            {
                get { return "NUMCHARCYCL"; }
            }

            public static string CHARTIME
            {
                get { return "CHARTIME"; }
            }

            public static string TXTPOLLNORM1CD2
            {
                get { return "TXTPOLLNORM1CD2"; }
            }

            public static string TXTPOLLNORM2CD2
            {
                get { return "TXTPOLLNORM2CD2"; }
            }

            public static string TXTPOLLNORM3CD2
            {
                get { return "TXTPOLLNORM3CD2"; }
            }

            public static string TXTPOLLNORM4CD2
            {
                get { return "TXTPOLLNORM4CD2"; }
            }

            public static string TXTPOLLNORM5CD2
            {
                get { return "TXTPOLLNORM5CD2"; }
            }

            public static string VAL
            {
                get { return "VAL"; }
            }

            public static string NUMWHEELS
            {
                get { return "NUMWHEELS"; }
            }

            public static string TYPESPARE
            {
                get { return "TYPESPARE"; }
            }

            public static string TYREFRONT
            {
                get { return "TYREFRONT"; }
            }

            public static string TYREREAR
            {
                get { return "TYREREAR"; }
            }

            public static string TXTBODYMCATCD2
            {
                get { return "TXTBODYMCATCD2"; }
            }

            public static string CONSGAS
            {
                get { return "CONSGAS"; }
            }

            public static string CONSGASURB
            {
                get { return "CONSGASURB"; }
            }

            public static string CONSGASLAND
            {
                get { return "CONSGASLAND"; }
            }

            public static string CONSGASTOT
            {
                get { return "CONSGASTOT"; }
            }

            public static string TXTCONSGASUNITCD
            {
                get { return "TXTCONSGASUNITCD"; }
            }

            public static string CONSURBIMP
            {
                get { return "CONSURBIMP"; }
            }

            public static string CONSLANDIMP
            {
                get { return "CONSLANDIMP"; }
            }

            public static string CONSTOTIMP
            {
                get { return "CONSTOTIMP"; }
            }


			#endregion
        }

    }
}