// AUTOGENERATED, 26.01.2010 17:01:13
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdEurotax
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ETGIMATECINF
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ETGIMATECINF));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string ID
            {
                get { return "ID"; }
            }

            public static string HEIGHT
            {
                get { return "HEIGHT"; }
            }

            public static string WIDTH
            {
                get { return "WIDTH"; }
            }

            public static string SIZENAME
            {
                get { return "SIZENAME"; }
            }

            public static string EXTENTION
            {
                get { return "EXTENTION"; }
            }

            public static string FILESIZE
            {
                get { return "FILESIZE"; }
            }

            public static string MODELY
            {
                get { return "MODELY"; }
            }


			#endregion
        }

    }
}