// AUTOGENERATED, 26.01.2010 17:01:13
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdEurotax
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ETGPRICEHISTORY
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ETGPRICEHISTORY));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string PRHMARKET
            {
                get { return "PRHMARKET"; }
            }

            public static string PRHVEHTYPE
            {
                get { return "PRHVEHTYPE"; }
            }

            public static string PRHNATCODE
            {
                get { return "PRHNATCODE"; }
            }

            public static string PRHCURRENCY
            {
                get { return "PRHCURRENCY"; }
            }

            public static string PRHRECSTATUS
            {
                get { return "PRHRECSTATUS"; }
            }

            public static string PRHRECDATE
            {
                get { return "PRHRECDATE"; }
            }

            public static string PRHNP1
            {
                get { return "PRHNP1"; }
            }

            public static string PRHNP2
            {
                get { return "PRHNP2"; }
            }

            public static string PRHTAXRT
            {
                get { return "PRHTAXRT"; }
            }

            public static string PRHTAX1
            {
                get { return "PRHTAX1"; }
            }

            public static string PRHTAX2
            {
                get { return "PRHTAX2"; }
            }

            public static string PRHVAL
            {
                get { return "PRHVAL"; }
            }

            public static string PRHNET
            {
                get { return "PRHNET"; }
            }

            public static string PRHREPLID
            {
                get { return "PRHREPLID"; }
            }

            public static string PRHVATAMOUNT
            {
                get { return "PRHVATAMOUNT"; }
            }

            public static string PRHGROSSNP3
            {
                get { return "PRHGROSSNP3"; }
            }

            public static string PRHRECYCLCOST
            {
                get { return "PRHRECYCLCOST"; }
            }

            public static string PRHTRPTCOST
            {
                get { return "PRHTRPTCOST"; }
            }

            public static string PRHTRPTCOSTVAT
            {
                get { return "PRHTRPTCOSTVAT"; }
            }

            public static string PRHIMMFEE
            {
                get { return "PRHIMMFEE"; }
            }

            public static string PRHVALUNTIL
            {
                get { return "PRHVALUNTIL"; }
            }

            public static string PRHPROVISIONAL
            {
                get { return "PRHPROVISIONAL"; }
            }


			#endregion
        }

    }
}