// AUTOGENERATED, 26.01.2010 17:01:13
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Cic.OpenLease.Model.DdEurotax
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class ETGTCERTDATACH
    {
    
        #region Private variables
        private static Cic.Basic.Data.Objects.Property.InfoPackageDictionary _InfoPackageDictionary;
        #endregion

        #region Methods
        public static Cic.Basic.Data.Objects.Property.InfoPackageDictionary DeliverInfoPackageDictionary()
        {
            if (_InfoPackageDictionary == null)
            {
                _InfoPackageDictionary = new Cic.Basic.Data.Objects.Property.InfoPackageDictionary(typeof(ETGTCERTDATACH));
            }

            return _InfoPackageDictionary;
        }
        #endregion
        
        public partial struct FieldNames
        {
            #region Properties
            public static string MARKET
            {
                get { return "MARKET"; }
            }

            public static string VEHTYPE
            {
                get { return "VEHTYPE"; }
            }

            public static string TGNR
            {
                get { return "TGNR"; }
            }

            public static string MAKE
            {
                get { return "MAKE"; }
            }

            public static string TYPE
            {
                get { return "TYPE"; }
            }

            public static string TECHTYP
            {
                get { return "TECHTYP"; }
            }

            public static string VINCODE
            {
                get { return "VINCODE"; }
            }

            public static string SEATS
            {
                get { return "SEATS"; }
            }

            public static string SEATSMAX
            {
                get { return "SEATSMAX"; }
            }

            public static string GEARBOX1
            {
                get { return "GEARBOX1"; }
            }

            public static string GEARBOX2
            {
                get { return "GEARBOX2"; }
            }

            public static string GEARBOX3
            {
                get { return "GEARBOX3"; }
            }

            public static string GEARBOX4
            {
                get { return "GEARBOX4"; }
            }

            public static string ENGINCODE
            {
                get { return "ENGINCODE"; }
            }

            public static string FUELTYPE
            {
                get { return "FUELTYPE"; }
            }

            public static string CAPACITY
            {
                get { return "CAPACITY"; }
            }

            public static string PERFORMANCE
            {
                get { return "PERFORMANCE"; }
            }

            public static string PERFORMREVS
            {
                get { return "PERFORMREVS"; }
            }

            public static string TORQUE
            {
                get { return "TORQUE"; }
            }

            public static string TORQUEREVS
            {
                get { return "TORQUEREVS"; }
            }

            public static string CURBWGT
            {
                get { return "CURBWGT"; }
            }

            public static string CURBWGTMAX
            {
                get { return "CURBWGTMAX"; }
            }

            public static string MAXWGT
            {
                get { return "MAXWGT"; }
            }

            public static string MAXWGTMAX
            {
                get { return "MAXWGTMAX"; }
            }

            public static string CAT
            {
                get { return "CAT"; }
            }

            public static string TRAILERBRKMAN
            {
                get { return "TRAILERBRKMAN"; }
            }

            public static string TRAILERBRKAUT
            {
                get { return "TRAILERBRKAUT"; }
            }

            public static string TRAILERUNBRKMAN
            {
                get { return "TRAILERUNBRKMAN"; }
            }

            public static string TRAILERUNBRKAUT
            {
                get { return "TRAILERUNBRKAUT"; }
            }

            public static string ROOFLOAD
            {
                get { return "ROOFLOAD"; }
            }

            public static string VMAXMAN
            {
                get { return "VMAXMAN"; }
            }

            public static string VMAXMANMAX
            {
                get { return "VMAXMANMAX"; }
            }

            public static string VMAXAUT
            {
                get { return "VMAXAUT"; }
            }

            public static string VMAXAUTMAX
            {
                get { return "VMAXAUTMAX"; }
            }

            public static string TYRE1
            {
                get { return "TYRE1"; }
            }

            public static string TYRE2
            {
                get { return "TYRE2"; }
            }

            public static string TYRE3
            {
                get { return "TYRE3"; }
            }

            public static string POLLUTNORM1
            {
                get { return "POLLUTNORM1"; }
            }

            public static string POLLUTNORM2
            {
                get { return "POLLUTNORM2"; }
            }

            public static string POLLUTNORM3
            {
                get { return "POLLUTNORM3"; }
            }

            public static string POLLUTNORM4
            {
                get { return "POLLUTNORM4"; }
            }

            public static string ENERGEFF1
            {
                get { return "ENERGEFF1"; }
            }

            public static string ENERGEFF2
            {
                get { return "ENERGEFF2"; }
            }

            public static string ENERGEFF3
            {
                get { return "ENERGEFF3"; }
            }

            public static string ENERGEFF4
            {
                get { return "ENERGEFF4"; }
            }

            public static string CO21
            {
                get { return "CO21"; }
            }

            public static string CO22
            {
                get { return "CO22"; }
            }

            public static string CO23
            {
                get { return "CO23"; }
            }

            public static string CO24
            {
                get { return "CO24"; }
            }

            public static string CONS1
            {
                get { return "CONS1"; }
            }

            public static string CONS2
            {
                get { return "CONS2"; }
            }

            public static string CONS3
            {
                get { return "CONS3"; }
            }

            public static string CONS4
            {
                get { return "CONS4"; }
            }

            public static string RECDATE
            {
                get { return "RECDATE"; }
            }


			#endregion
        }

    }
}