// AUTOGENERATED, 10/02/2010 17:11:43
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Cic.OpenOne.Common.Util.Config;
namespace Cic.OpenLease.Model.DdCt
{
    [System.CodeDom.Compiler.GeneratedCode("Cic.OpenLease.CodeGenerator", "1.0.0.0")]
    [System.CLSCompliant(true)]
    public partial class CtExtendedEntities : CtEntities
    {
    
		
        #region Constructors
        public CtExtendedEntities() :
           base(ConnectionStringBuilder.DeliverConnectionString(typeof (CtEntities), "DdCt"))
            
        {
        }

        #endregion

		
    }
}
